from setuptools import setup, find_packages

setup(
    name="fluxlib-py",
    version="0.3.0",
    packages=find_packages(),
    description="FluxLib for Python",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Eugene Zimnitskiy",
    author_email="karpotkin@gmail.com",
    url="https://github.com/flux-agi/fluxlib-py",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.6",
    install_requires=[
        "requests>=2.25.0",
        "websockets>=10.0",
        "aiohttp>=3.8.0",
        "pydantic>=1.8.0",
        "python-dotenv>=0.19.0",
        "typing-extensions>=4.0.0",
        "urllib3>=1.26.0",
        "certifi>=2021.5.30",
        "charset-normalizer>=2.0.0",
        "idna>=3.2",
        "multidict>=5.1.0",
        "async-timeout>=4.0.0",
        "frozenlist>=1.1.1",
        "attrs>=21.2.0",
        "yarl>=1.6.2",
        "email-validator>=1.1.3",
    ],
) 