from setuptools import setup, find_packages

setup(
    name="orbit-orator",
    version="0.9.9.4",
    description="A simple but powerful ORM for Python, inspired by Laravel's Eloquent",
    author="Sébastien Eustace, Maxiaoyu",
    author_email="sebastien@eustace.io, maxiaoyu@example.com",
    license="MIT",
    url="https://github.com/maxiaoyu/orator",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        "inflection>=0.5.1",
        "six>=1.10.0",
        "simplejson>=3.10.0",
        "pendulum>=2.0.0",
        "pyyaml>=6.0.1,<7.0.0",
        "cleo>=0.8.1",
        "packaging>=21.0",
        "typing-extensions>=4.0.0",
        "pytzdata>=2020.1",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
) 