# This file was auto-generated by Fern from our API Definition.

import typing
from .agents_search_response_agents_item_multi_agent_group_item_agent_ids_max_turns_item import (
    AgentsSearchResponseAgentsItemMultiAgentGroupItemAgentIdsMaxTurnsItem,
)

AgentsSearchResponseAgentsItemMultiAgentGroupItemAgentIdsMaxTurns = typing.Union[
    float,
    typing.Optional[str],
    typing.List[typing.Optional[AgentsSearchResponseAgentsItemMultiAgentGroupItemAgentIdsMaxTurnsItem]],
    typing.Optional[typing.Any],
]
