# Generated by Django 3.2.20 on 2025-03-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federated_content_connector', '0004_coursedetails_course_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='external_identifier',
            field=models.CharField(blank=True, default='', help_text='The identifier of the course in the external system', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='course_key',
            field=models.CharField(blank=True, default='', help_text='The top-level course key associated with the course run key', max_length=255),
        ),
    ]
