
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-25T09:39:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1d739fcf93c41f024d3a6d57d9682dd50c7ca1a",
 "version": "1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
