from __future__ import annotations
from . import algorithms

__all__ = ["Highlight", "algorithms"]

class Highlight:
    def __str__(self) -> str: ...
    def get_most_frequent_rhs_value_indices(self) -> list[int]: ...
    def get_most_frequent_rhs_values(self) -> list[str]: ...
    def get_occurences_indices(self) -> list[int]: ...
    def get_rhs_values(self) -> list[str]: ...
    def to_long_string(self) -> str: ...
    def to_short_string(self) -> str: ...
    @property
    def distinct_rhs_values_number(self) -> int: ...
    @property
    def lhs_value(self) -> str: ...
    @property
    def occurences_number(self) -> int: ...
