# Generated by Django 4.1 on 2022-08-31 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiakas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lasku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('asiakas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laskut', to='testit.asiakas')),
            ],
        ),
        migrations.CreateModel(
            name='Paamies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=11)),
                ('selite', models.CharField(max_length=255)),
                ('lasku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testit.lasku')),
            ],
        ),
        migrations.CreateModel(
            name='Osoite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osoite', models.CharField(max_length=255)),
                ('asiakas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osoitteet', to='testit.asiakas')),
            ],
        ),
        migrations.AddField(
            model_name='lasku',
            name='paamies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testit.paamies'),
        ),
    ]
