"""Cookie constants for dnoticias_auth"""

ACCESS_TOKEN = "ACCESS_TOKEN"
ACCESS_TOKEN_EXPIRATION = "ACCESS_TOKEN_EXPIRATION"
LOGIN_NEXT = "LOGIN_NEXT"
KC_SESSION_ID = "KC_SESSION_ID"
OLD_KC_SESSION_ID = "OLD_KC_SESSION_ID"
KC_USER_ID = "USER_ID"
