# coding: utf-8

"""
    Akrimanager Backend v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from akridata_akrimanager_v2.configuration import Configuration


class ImportFeatureDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'feature_m': 'int',
        'feature_n': 'int',
        'feature_f': 'int'
    }

    attribute_map = {
        'feature_m': 'feature_m',
        'feature_n': 'feature_n',
        'feature_f': 'feature_f'
    }

    def __init__(self, feature_m=1, feature_n=1, feature_f=None, local_vars_configuration=None):  # noqa: E501
        """ImportFeatureDetails - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._feature_m = None
        self._feature_n = None
        self._feature_f = None
        self.discriminator = None

        if feature_m is not None:
            self.feature_m = feature_m
        if feature_n is not None:
            self.feature_n = feature_n
        self.feature_f = feature_f

    @property
    def feature_m(self):
        """Gets the feature_m of this ImportFeatureDetails.  # noqa: E501


        :return: The feature_m of this ImportFeatureDetails.  # noqa: E501
        :rtype: int
        """
        return self._feature_m

    @feature_m.setter
    def feature_m(self, feature_m):
        """Sets the feature_m of this ImportFeatureDetails.


        :param feature_m: The feature_m of this ImportFeatureDetails.  # noqa: E501
        :type feature_m: int
        """

        self._feature_m = feature_m

    @property
    def feature_n(self):
        """Gets the feature_n of this ImportFeatureDetails.  # noqa: E501


        :return: The feature_n of this ImportFeatureDetails.  # noqa: E501
        :rtype: int
        """
        return self._feature_n

    @feature_n.setter
    def feature_n(self, feature_n):
        """Sets the feature_n of this ImportFeatureDetails.


        :param feature_n: The feature_n of this ImportFeatureDetails.  # noqa: E501
        :type feature_n: int
        """

        self._feature_n = feature_n

    @property
    def feature_f(self):
        """Gets the feature_f of this ImportFeatureDetails.  # noqa: E501


        :return: The feature_f of this ImportFeatureDetails.  # noqa: E501
        :rtype: int
        """
        return self._feature_f

    @feature_f.setter
    def feature_f(self, feature_f):
        """Sets the feature_f of this ImportFeatureDetails.


        :param feature_f: The feature_f of this ImportFeatureDetails.  # noqa: E501
        :type feature_f: int
        """
        if self.local_vars_configuration.client_side_validation and feature_f is None:  # noqa: E501
            raise ValueError("Invalid value for `feature_f`, must not be `None`")  # noqa: E501

        self._feature_f = feature_f

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImportFeatureDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImportFeatureDetails):
            return True

        return self.to_dict() != other.to_dict()
