# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gravi/rest/ai/ask.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'gravi/rest/ai/ask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gs_options_pb2 as gs__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gravi/rest/ai/ask.proto\x12\rgravi.rest.ai\x1a\x10gs-options.proto\"b\n\x0f\x41skShrekRequest\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12-\n\x05voice\x18\x02 \x01(\x0b\x32\x1c.gravi.rest.ai.VoiceQuestionH\x00:\x04\x88\xb5\x18\x01\x42\n\n\x08question\"$\n\rVoiceQuestion\x12\r\n\x05voice\x18\x02 \x01(\x0c:\x04\x88\xb5\x18\x01\"U\n\x10\x41skShrekResponse\x12)\n\x06quotes\x18\x01 \x03(\x0b\x32\x19.gravi.rest.ai.ShrekQuote\x12\x10\n\x08question\x18\x02 \x01(\t:\x04\x88\xb5\x18\x01\"\x8c\x01\n\nShrekQuote\x12/\n\x05video\x18\x01 \x01(\x0b\x32\x1e.gravi.rest.ai.ShrekQuoteVideoH\x00\x12<\n\x07summary\x18\x02 \x01(\x0b\x32).gravi.rest.ai.ShrekQuoteGeneratedSummaryH\x00:\x04\x88\xb5\x18\x01\x42\t\n\x07payload\"W\n\x0fShrekQuoteVideo\x12\x11\n\tsignedUrl\x18\x01 \x01(\t\x12\x18\n\x10startingPosition\x18\x02 \x01(\x02\x12\x11\n\tchunkHint\x18\x03 \x01(\t:\x04\x88\xb5\x18\x01\"3\n\x1aShrekQuoteGeneratedSummary\x12\x0f\n\x07summary\x18\x01 \x01(\t:\x04\x88\xb5\x18\x01\x42\x45\n\x0c\x63om.gs.pb.aiP\x01Z3gravitysketch.com/platform/go/vrproto/gravi/rest/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gravi.rest.ai.ask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.gs.pb.aiP\001Z3gravitysketch.com/platform/go/vrproto/gravi/rest/ai'
  _globals['_ASKSHREKREQUEST']._loaded_options = None
  _globals['_ASKSHREKREQUEST']._serialized_options = b'\210\265\030\001'
  _globals['_VOICEQUESTION']._loaded_options = None
  _globals['_VOICEQUESTION']._serialized_options = b'\210\265\030\001'
  _globals['_ASKSHREKRESPONSE']._loaded_options = None
  _globals['_ASKSHREKRESPONSE']._serialized_options = b'\210\265\030\001'
  _globals['_SHREKQUOTE']._loaded_options = None
  _globals['_SHREKQUOTE']._serialized_options = b'\210\265\030\001'
  _globals['_SHREKQUOTEVIDEO']._loaded_options = None
  _globals['_SHREKQUOTEVIDEO']._serialized_options = b'\210\265\030\001'
  _globals['_SHREKQUOTEGENERATEDSUMMARY']._loaded_options = None
  _globals['_SHREKQUOTEGENERATEDSUMMARY']._serialized_options = b'\210\265\030\001'
  _globals['_ASKSHREKREQUEST']._serialized_start=60
  _globals['_ASKSHREKREQUEST']._serialized_end=158
  _globals['_VOICEQUESTION']._serialized_start=160
  _globals['_VOICEQUESTION']._serialized_end=196
  _globals['_ASKSHREKRESPONSE']._serialized_start=198
  _globals['_ASKSHREKRESPONSE']._serialized_end=283
  _globals['_SHREKQUOTE']._serialized_start=286
  _globals['_SHREKQUOTE']._serialized_end=426
  _globals['_SHREKQUOTEVIDEO']._serialized_start=428
  _globals['_SHREKQUOTEVIDEO']._serialized_end=515
  _globals['_SHREKQUOTEGENERATEDSUMMARY']._serialized_start=517
  _globals['_SHREKQUOTEGENERATEDSUMMARY']._serialized_end=568
# @@protoc_insertion_point(module_scope)
