# coding: utf-8

"""
    AristaFlowREST/ExecutionManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ActivityReferenceData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sub_class': 'str',
        'act': 'EbpInstanceReference'
    }

    attribute_map = {
        'sub_class': 'subClass',
        'act': 'act'
    }

    def __init__(self, sub_class=None, act=None):  # noqa: E501
        """ActivityReferenceData - a model defined in Swagger"""  # noqa: E501
        self._sub_class = None
        self._act = None
        if not(hasattr(self, "discriminator")) or not(self.discriminator):
            self.discriminator = None
        if sub_class is not None:
            self.sub_class = sub_class
        self.act = act

    @property
    def sub_class(self):
        """Gets the sub_class of this ActivityReferenceData.  # noqa: E501


        :return: The sub_class of this ActivityReferenceData.  # noqa: E501
        :rtype: str
        """
        return self._sub_class

    @sub_class.setter
    def sub_class(self, sub_class):
        """Sets the sub_class of this ActivityReferenceData.


        :param sub_class: The sub_class of this ActivityReferenceData.  # noqa: E501
        :type: str
        """

        self._sub_class = sub_class

    @property
    def act(self):
        """Gets the act of this ActivityReferenceData.  # noqa: E501


        :return: The act of this ActivityReferenceData.  # noqa: E501
        :rtype: EbpInstanceReference
        """
        return self._act

    @act.setter
    def act(self, act):
        """Sets the act of this ActivityReferenceData.


        :param act: The act of this ActivityReferenceData.  # noqa: E501
        :type: EbpInstanceReference
        """
        if act is None:
            raise ValueError("Invalid value for `act`, must not be `None`")  # noqa: E501

        self._act = act

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActivityReferenceData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActivityReferenceData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
