
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-25T09:07:13-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "f52807e5c7ef5abb74a0d6550ba1a62e53fa1d45",
 "version": "2.57.1b9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
