# This file was auto-generated by Fern from our API Definition.

import typing
from .templates_create_agents_response_agents_item_tools_item_source_code_item import (
    TemplatesCreateAgentsResponseAgentsItemToolsItemSourceCodeItem,
)

TemplatesCreateAgentsResponseAgentsItemToolsItemSourceCode = typing.Union[
    str,
    typing.Optional[str],
    typing.List[typing.Optional[TemplatesCreateAgentsResponseAgentsItemToolsItemSourceCodeItem]],
]
