# Generated by Django 4.0.3 on 2022-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmanager', '0006_watchconfig_config_type_alter_watchconfig_webhooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook',
            old_name='webhook',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='watchconfig',
            name='webhooks',
        ),
        migrations.AddField(
            model_name='watchconfig',
            name='fail_webhooks',
            field=models.ManyToManyField(blank=True, related_name='fail_webhooks', to='marketmanager.webhook', verbose_name='Webhooks'),
        ),
        migrations.AddField(
            model_name='watchconfig',
            name='success_webhooks',
            field=models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on WatchConfigs that dont have any issues', related_name='success_webhooks', to='marketmanager.webhook', verbose_name='Success Webhooks'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
