# Generated by Django 4.0.6 on 2022-08-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmanager', '0031_alter_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchconfig',
            name='managed_watch_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketmanager.managedwatchconfig', verbose_name='Managed Watch Configs'),
        ),
    ]
