# coding: utf-8

"""
    Daytona Workspaces

    Daytona Workspaces API Docs

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_api_client.models.session_execute_response import SessionExecuteResponse

class TestSessionExecuteResponse(unittest.TestCase):
    """SessionExecuteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionExecuteResponse:
        """Test SessionExecuteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionExecuteResponse`
        """
        model = SessionExecuteResponse()
        if include_optional:
            return SessionExecuteResponse(
                cmd_id = 'cmd-123',
                output = 'total 20
drwxr-xr-x  4 user group  128 Mar 15 10:30 .',
                exit_code = 0
            )
        else:
            return SessionExecuteResponse(
        )
        """

    def testSessionExecuteResponse(self):
        """Test SessionExecuteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
