# coding: utf-8

"""
    Daytona Workspaces

    Daytona Workspaces API Docs

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_api_client.api.images_api import ImagesApi


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagesApi()

    def tearDown(self) -> None:
        pass

    def test_create_image(self) -> None:
        """Test case for create_image

        Create a new image
        """
        pass

    def test_get_all_images(self) -> None:
        """Test case for get_all_images

        List all images
        """
        pass

    def test_remove_image(self) -> None:
        """Test case for remove_image

        Delete image
        """
        pass

    def test_toggle_image_state(self) -> None:
        """Test case for toggle_image_state

        Toggle image state
        """
        pass


if __name__ == '__main__':
    unittest.main()
