class Mdl_JcModelDBData_Py:
    m_LoadZHFloatList: list[Mdl_jc_LoadZH_Float]
    m_jcVerList: list[Mdl_jc_ver]
    m_jcNodeList: list[Mdl_jc_node]
    m_jcAppDJList: list[Mdl_jc_app_DJ]
    m_jcIwagList: list[Mdl_jc_iwag]
    m_jcAppBraceList: list[Mdl_jc_app_brace]
    m_jcAppColumnList: list[Mdl_jc_app_column]
    m_jcAppDaisList: list[Mdl_jc_app_dais]
    m_jcAppElevatorList: list[Mdl_jc_app_Elevator]
    m_jcAppFbeamList: list[Mdl_jc_app_fbeam]
    m_jcAppFwallList: list[Mdl_jc_app_fwall]
    m_jcAppLLList: list[Mdl_jc_app_LL]
    m_jcAppPileList: list[Mdl_jc_app_Pile]
    m_jcAppTJList: list[Mdl_jc_app_TJ]
    m_jcAppwallList: list[Mdl_jc_app_wall]
    m_jcAppWaterPipeList: list[Mdl_jc_app_WaterPipe]
    m_jcAppWaterPitList: list[Mdl_jc_app_WaterPit]
    m_jcAxisList: list[Mdl_jc_axis]
    m_jcCalParaList: list[Mdl_jc_CalPara]
    m_jcDaisCirList: list[Mdl_jc_dais_Cir]
    m_jcDaisPtList: list[Mdl_jc_dais_pt]
    m_jcDaisStepHList: list[Mdl_jc_dais_stepH]
    m_jcDEFBraceList: list[Mdl_jc_DEF_brace]
    m_jcDEFColumnList: list[Mdl_jc_DEF_column]
    m_jcDEFDaisList: list[Mdl_jc_DEF_dais]
    m_jcDEFDJList: list[Mdl_jc_DEF_DJ]
    m_jcDEFElevatorList: list[Mdl_jc_DEF_Elevator]
    m_jcDEFFbeamList: list[Mdl_jc_DEF_fbeam]
    m_jcDEFFwallList: list[Mdl_jc_DEF_fwall]
    m_jcDEFLLList: list[Mdl_jc_DEF_LL]
    m_jcDEFPileList: list[Mdl_jc_DEF_Pile]
    m_jcDEFRaftYList: list[Mdl_jc_DEF_RaftY]
    m_jcDEFTJList: list[Mdl_jc_DEF_TJ]
    m_jcDEFWallList: list[Mdl_jc_DEF_wall]
    m_jcDEFWaterPipeList: list[Mdl_jc_DEF_WaterPipe]
    m_jcDEFWaterPitList: list[Mdl_jc_DEF_WaterPit]
    m_jcDEFZDList: list[Mdl_jc_DEF_ZD]
    m_jcHouJiaoDaiList: list[Mdl_jc_HouJiaoDai]
    m_jcLoadsList: list[Mdl_jc_Loads]
    m_jcLoadsFuJiaLineList: list[Mdl_jc_LoadsFuJia_Line]
    m_jcLoadsFuJiaPointList: list[Mdl_jc_LoadsFuJia_Point]
    m_jcLoadsLineList: list[Mdl_jc_LoadsLine]
    m_jcLoadsDiaoCheList: list[Mdl_jc_Loads_diaoche]
    m_jcLoadsLineDiaoCheList: list[Mdl_jc_Loads_line_diaoche]
    m_jcLoadsZDYLineList: list[Mdl_jc_Loads_ZiDingYi_Line]
    m_jcLoadsZDYPointList: list[Mdl_jc_Loads_ZiDingYi_Point]
    m_jcLoadV2ArcShowList: list[Mdl_jc_LoadV2_Arc_Show]
    m_jcLoadV2LineCalList: list[Mdl_jc_LoadV2_Line_Cal]
    m_jcLoadV2LineShowList: list[Mdl_jc_LoadV2_Line_Show]
    m_jcLoadV2LoadCaseList: list[Mdl_jc_LoadV2_LoadCase]
    m_jcLoadV2PointList: list[Mdl_jc_LoadV2_Point]
    m_jcLoadZhuHeList: list[Mdl_jc_LoadZhuHe]
    m_jcLoadZHRealList: list[Mdl_jc_LoadZH_real]
    m_jcLoadZHFloatList: list[Mdl_jc_LoadZH_Float]
    m_jcLoadArcList: list[Mdl_jc_Load_Arc]
    m_jcLoadChoseList: list[Mdl_jc_load_Chose]
    m_jcLoadLineList: list[Mdl_jc_Load_Line]
    m_jcLoadZDYArcList: list[Mdl_jc_Load_ZiDingYi_Arc]
    m_jcLoadZDYLineList: list[Mdl_jc_load_ZiDingYi_Line]
    m_jcParaNumsList: list[Mdl_jc_ParaNums]
    m_jcPointsLoadList: list[Mdl_jc_Points_Load]
    m_jcRaftCornerPointList: list[Mdl_jc_RaftCornerPoint]
    m_jcRaftSlabList: list[Mdl_jc_RaftSlab]
    m_jcRaftYInfoList: list[Mdl_jc_RaftYInfo]
    m_jcZDYNameList: list[Mdl_jc_ZiDingYi_Name]
    m_jcChildRaftList: list[Mdl_jc_ChildRaft]
class Mdl_JcModelDBData:
    m_LoadZHFloatList: list[Mdl_jc_LoadZH_Float]
    m_jcVerList: list[Mdl_jc_ver]
    m_jcNodeList: list[Mdl_jc_node]
    m_jcAppDJList: list[Mdl_jc_app_DJ]
    m_jcIwagList: list[Mdl_jc_iwag]
    m_jcAppBraceList: list[Mdl_jc_app_brace]
    m_jcAppColumnList: list[Mdl_jc_app_column]
    m_jcAppDaisList: list[Mdl_jc_app_dais]
    m_jcAppElevatorList: list[Mdl_jc_app_Elevator]
    m_jcAppFbeamList: list[Mdl_jc_app_fbeam]
    m_jcAppFwallList: list[Mdl_jc_app_fwall]
    m_jcAppLLList: list[Mdl_jc_app_LL]
    m_jcAppPileList: list[Mdl_jc_app_Pile]
    m_jcAppTJList: list[Mdl_jc_app_TJ]
    m_jcAppwallList: list[Mdl_jc_app_wall]
    m_jcAppWaterPipeList: list[Mdl_jc_app_WaterPipe]
    m_jcAppWaterPitList: list[Mdl_jc_app_WaterPit]
    m_jcAxisList: list[Mdl_jc_axis]
    m_jcCalParaList: list[Mdl_jc_CalPara]
    m_jcDaisCirList: list[Mdl_jc_dais_Cir]
    m_jcDaisPtList: list[Mdl_jc_dais_pt]
    m_jcDaisStepHList: list[Mdl_jc_dais_stepH]
    m_jcDEFBraceList: list[Mdl_jc_DEF_brace]
    m_jcDEFColumnList: list[Mdl_jc_DEF_column]
    m_jcDEFDaisList: list[Mdl_jc_DEF_dais]
    m_jcDEFDJList: list[Mdl_jc_DEF_DJ]
    m_jcDEFElevatorList: list[Mdl_jc_DEF_Elevator]
    m_jcDEFFbeamList: list[Mdl_jc_DEF_fbeam]
    m_jcDEFFwallList: list[Mdl_jc_DEF_fwall]
    m_jcDEFLLList: list[Mdl_jc_DEF_LL]
    m_jcDEFPileList: list[Mdl_jc_DEF_Pile]
    m_jcDEFRaftYList: list[Mdl_jc_DEF_RaftY]
    m_jcDEFTJList: list[Mdl_jc_DEF_TJ]
    m_jcDEFWallList: list[Mdl_jc_DEF_wall]
    m_jcDEFWaterPipeList: list[Mdl_jc_DEF_WaterPipe]
    m_jcDEFWaterPitList: list[Mdl_jc_DEF_WaterPit]
    m_jcDEFZDList: list[Mdl_jc_DEF_ZD]
    m_jcHouJiaoDaiList: list[Mdl_jc_HouJiaoDai]
    m_jcLoadsList: list[Mdl_jc_Loads]
    m_jcLoadsFuJiaLineList: list[Mdl_jc_LoadsFuJia_Line]
    m_jcLoadsFuJiaPointList: list[Mdl_jc_LoadsFuJia_Point]
    m_jcLoadsLineList: list[Mdl_jc_LoadsLine]
    m_jcLoadsDiaoCheList: list[Mdl_jc_Loads_diaoche]
    m_jcLoadsLineDiaoCheList: list[Mdl_jc_Loads_line_diaoche]
    m_jcLoadsZDYLineList: list[Mdl_jc_Loads_ZiDingYi_Line]
    m_jcLoadsZDYPointList: list[Mdl_jc_Loads_ZiDingYi_Point]
    m_jcLoadV2ArcShowList: list[Mdl_jc_LoadV2_Arc_Show]
    m_jcLoadV2LineCalList: list[Mdl_jc_LoadV2_Line_Cal]
    m_jcLoadV2LineShowList: list[Mdl_jc_LoadV2_Line_Show]
    m_jcLoadV2LoadCaseList: list[Mdl_jc_LoadV2_LoadCase]
    m_jcLoadV2PointList: list[Mdl_jc_LoadV2_Point]
    m_jcLoadZhuHeList: list[Mdl_jc_LoadZhuHe]
    m_jcLoadZHRealList: list[Mdl_jc_LoadZH_real]
    m_jcLoadZHFloatList: list[Mdl_jc_LoadZH_Float]
    m_jcLoadArcList: list[Mdl_jc_Load_Arc]
    m_jcLoadChoseList: list[Mdl_jc_load_Chose]
    m_jcLoadLineList: list[Mdl_jc_Load_Line]
    m_jcLoadZDYArcList: list[Mdl_jc_Load_ZiDingYi_Arc]
    m_jcLoadZDYLineList: list[Mdl_jc_load_ZiDingYi_Line]
    m_jcParaNumsList: list[Mdl_jc_ParaNums]
    m_jcPointsLoadList: list[Mdl_jc_Points_Load]
    m_jcRaftCornerPointList: list[Mdl_jc_RaftCornerPoint]
    m_jcRaftSlabList: list[Mdl_jc_RaftSlab]
    m_jcRaftYInfoList: list[Mdl_jc_RaftYInfo]
    m_jcZDYNameList: list[Mdl_jc_ZiDingYi_Name]
    m_jcChildRaftList: list[Mdl_jc_ChildRaft]
    def ToPyList(self) -> Mdl_JcModelDBData_Py: ...
class Mdl_jc_ver:
    ID: int
    version: str
    CreateVer: str
    strPath: str
    projflag: int
    LoadFlag: int
class Mdl_jc_node:
    ID: int
    X: float
    Y: float
    Z: float
    id_old: int
    jcAdd: Int64
class Mdl_jc_app_DJ:
    ID: int
    nj: int
    kind: int
    ex: float
    ey: float
    ang: float
    nMarkCho: int
    dBotElevat: float
    isBGAbs: int
    padd: float
    fk: float
    amb: float
    amd: float
    lNewFlag: int
    fk_dd: float
    HSoil_dd: float
    ex2: float
    ey2: float
    ang2: float
    baseZ: float
    bFea: int
    fk_Euro: float
class Mdl_jc_iwag:
    ID: int
    nbg: int
    ned: int
    ngrid: int
    lID: int
    nAxis: int
    nCeng: int
    id_old: int
    jcAdd: int
    lIDRaft: int
    lIDDefY_L: int
    lIDDefY_R: int
    cName: str
class Mdl_jc_app_brace:
    ID: int
    nj: int
    kind: int
    ex1: int
    ey1: int
    ez1: int
    ex2: int
    ey2: int
    ez2: int
    ang: float
    ex: float
    ey: float
    nodeId: float
    idUp: int
    vX: float
    vY: float
    vZ: float
    ptX: float
    ptY: float
    ptZ: float
class Mdl_jc_app_column:
    ID: int
    nj: int
    kind: int
    ex: float
    ey: float
    ez: float
    ang: float
    lKJZKind: int
    lZDKind: int
    zd_ec: int
    zd_nc: int
    hgh: float
    baseZ: int
    idUp: int
    levelh: int
class Mdl_jc_app_dais:
    ID: int
    kind: int
    nj: int
    ex: float
    ey: float
    ang: float
    nMarkCho: int
    idaispilelen: float
    dBotElevat: float
    isBGAbs: int
    padd: int
    fk: float
    amb: float
    amd: float
    lNewFlag: int
    fk_dd: float
    HSoil_dd: float
    baseZ: int
    pile_peijin_para: str
    Fumozupara: str
    bFea: int
    fk_Euro: float
class Mdl_jc_app_Elevator:
    ID: int
    kind: int
    nRaftID: int
    ang: float
    cenx: float
    ceny: float
    npt: int
    ptx: str
    pty: str
class Mdl_jc_app_fbeam:
    ID: int
    nbg: int
    ned: int
    kind: int
    ec: int
    ngrid: int
    ngrid2: int
    nMarkCho: int
    dBotElevat: float
    isBGAbs: int
    fl_njl: float
    fl_njr: float
    padd: int
    fk: float
    amb: float
    amd: float
    fk_dd: float
    HSoil_dd: float
    jcAdd: int
    baseZ: float
    idUp: float
    strY: str
    SoilK: float
    fk_Euro: float
class Mdl_jc_app_fwall:
    ID: int
    nbg: int
    ned: int
    kind: int
    ec: int
    ngrid: int
    hgh: float
class Mdl_jc_app_LL:
    ID: int
    nbg: int
    ned: int
    kind: int
    ec: int
    fMD: float
    fML: float
    dBotElevat: float
    isBGAbs: int
    ngrid: int
    iHinge: int
class Mdl_jc_app_Pile:
    ID: int
    x: float
    y: float
    z: int
    kind: int
    ang: float
    NIK: int
    fKn: int
    fKm: int
    fALFQ: int
    DaisFlag: int
    idaispilelen: float
    lNewFlag: int
    idUp: int
    pile_peijin_para: str
    Fumozupara: str
class Mdl_jc_app_TJ:
    ID: int
    nbg: int
    ned: int
    kind: int
    ec: int
    ngrid: int
    nMarkCho: int
    dBotElevat: float
    isBGAbs: int
    padd: int
    fk: float
    amb: float
    amd: float
    lNewFlag: int
    fk_dd: float
    HSoil_dd: float
    fk_Euro: float
class Mdl_jc_app_wall:
    ID: int
    nbg: int
    ned: int
    kind: int
    ec: int
    ez: int
    ngrid: int
    hgh: float
    ndist_bg: float
    nlen_hole: float
    nStyle: int
    baseZ: float
    starth: int
    endh: int
    levelh: int
    ndist_ez: int
    nhei_hole: int
class Mdl_jc_app_WaterPipe:
    ID: int
    kind: int
    nRaftID: int
    npt: int
    ptx: str
    pty: str
class Mdl_jc_app_WaterPit:
    ID: int
    kind: int
    nRaftID: int
    ang: float
    cenx: float
    ceny: float
    npt: int
    ptx: str
    pty: str
class Mdl_jc_axis:
    ID: int
    j1: int
    j2: int
    ik: int
    id_old: int
    cname: int
    nCeng: str
    newName: str
    newCeng: int
class Mdl_jc_CalPara:
    ID: int
    strName: str
    strValue: str
    strSecName: str
class Mdl_jc_dais_Cir:
    ID: int
    DaisFlag: int
    D: float
class Mdl_jc_dais_pt:
    ID: int
    DaisFlag: int
    nstep: int
    x: float
    y: float
    z: int
class Mdl_jc_dais_stepH:
    ID: int
    DaisFlag: int
    nstep: int
    H: int
class Mdl_jc_DEF_brace:
    ID: int
    k: int
    b: int
    h: int
    u: int
    t: int
    d: int
    f: int
    l: int
    m: int
    p: int
    name: str
    igzz: int
    b1: int
    lID: int
    Poly: str
    bb: int
    hh: int
class Mdl_jc_DEF_column:
    ID: int
    k: int
    b: int
    h: int
    u: int
    t: int
    d: int
    f: int
    l: int
    m: int
    p: int
    name: str
    igzz: int
    b1: int
    lID: int
    Poly: str
    bb: int
    hh: int
class Mdl_jc_DEF_dais:
    ID: int
    ns: int
    means: int
    nstep: int
    npile: int
    DaisFlag: int
    ecx: int
    ecy: int
    lID: int
    lNewFlag: int
    lIsUsed: int
class Mdl_jc_DEF_DJ:
    ID: int
    kind: int
    n: int
    ak: int
    padthick: int
    cupdist: int
    asx: int
    asy: int
    ecx: int
    ecy: int
    s0: int
    s1: int
    s2: int
    s3: int
    s4: int
    b0: int
    b1: int
    b2: int
    b3: int
    b4: int
    h0: int
    h1: int
    h2: int
    h3: int
    h4: int
    lID: int
    lNewFlag: int
    lIsUsed: int
    lBeamB1: int
    lBeamB2: int
    lBeamH1: int
    lBeamH2: int
    lBeamNums: int
    lDis1: int
    lDis2: int
    lBeamBearing: int
class Mdl_jc_DEF_Elevator:
    ID: int
    lID: int
    shape: int
    rectL: int
    rectB: int
    depth: int
    botThick: int
    nEdge: int
    horzDist_vec: str
    vertDist_vec: str
    slope_vec: str
    equalSize: int
class Mdl_jc_DEF_fbeam:
    ID: int
    b: int
    h: int
    bb: int
    h1: int
    h2: int
    ec: int
    lID: int
    idUp: int
class Mdl_jc_DEF_fwall:
    ID: int
    lW: int
    lID: int
class Mdl_jc_DEF_LL:
    ID: int
    B: int
    H: int
    zj: int
    gj: int
    lID: int
class Mdl_jc_DEF_Pile:
    ID: int
    B: int
    H: int
    F1: float
    means: int
    topd: int
    w: int
    r2: int
    toph_u: int
    toph_m: int
    toph_b: int
    name: int
    lID: int
    F0: float
    F2: float
    idUp: int
    weight: float
    blade_D: int
    blade_dis: int
class Mdl_jc_DEF_RaftY:
    ID: int
    B: int
    H: int
    lID: int
class Mdl_jc_DEF_TJ:
    ID: int
    kind: int
    b: int
    h: int
    area: int
    length: int
    b1: int
    h1: int
    WLb: int
    WLh: int
    ec: int
    zj: int
    BTop4: int
    tana01: int
    gj: int
    zj_l: int
    gj_l: int
    HAll: int
    BTop6: int
    HEndL: int
    HEndR: int
    bw1: int
    bw2: int
    wSpace: int
    lID: int
    lNewFlag: int
    lIsUsed: int
    lArea_b: int
class Mdl_jc_DEF_wall:
    ID: int
    lW: int
    lID: int
    k: int
    m: int
class Mdl_jc_DEF_WaterPipe:
    ID: int
    lID: int
    shape: int
    rectB: int
    rectH: int
    arcH: float
class Mdl_jc_DEF_WaterPit:
    ID: int
    lID: int
    shape: int
    rectL: int
    rectB: int
    depth: int
    botThick: int
    nEdge: int
    horzDist_vec: str
    vertDist_vec: str
    slope_vec: str
    equalSize: int
class Mdl_jc_DEF_ZD:
    ID: int
    x: int
    y: int
    h: int
    h1: int
    lID: int
    kind: int
    idUp: int
    ex: int
    ey: int
    disL: float
    disR: float
    disU: float
    disD: float
class Mdl_jc_HouJiaoDai:
    ID: int
    xx: float
    yy: float
    ww: int
    lID: int
    nn: int
class Mdl_jc_Loads:
    ID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    data6: float
    data7: float
    data8: float
    data9: float
    lFlag: int
    strTN: str
    lIndex: int
    lCustom: int
class Mdl_jc_LoadsFuJia_Line:
    ID: int
    lID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    mark0: int
    jcAdd: int
class Mdl_jc_LoadsFuJia_Point:
    ID: int
    lID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    data6: float
    data7: float
    data8: float
    data9: float
    mark0: int
class Mdl_jc_LoadsLine:
    ID: int
    lID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    data6: float
    data7: float
    data8: float
    data9: float
    lFlag: int
    jcAdd: int
    lCustom: int
class Mdl_jc_Loads_diaoche:
    ID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    data6: float
    data7: float
    data8: float
    data9: float
    lFlag: int
    strTN: str
    lIndex: int
class Mdl_jc_Loads_line_diaoche:
    ID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    data6: float
    data7: float
    data8: float
    data9: float
    lFlag: int
    strTN: str
    lIndex: int
class Mdl_jc_Loads_ZiDingYi_Line:
    ID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    data6: float
    data7: float
    data8: float
    data9: float
    data10: float
    data11: float
    data12: float
    data13: float
    data14: float
    data15: float
    data16: float
    data17: float
    data18: float
    data19: float
    lFlag: int
    strTN: str
    lIndex: int
    data_Array: str
class Mdl_jc_Loads_ZiDingYi_Point:
    ID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    data6: float
    data7: float
    data8: float
    data9: float
    data10: float
    data11: float
    data12: float
    data13: float
    data14: float
    data15: float
    data16: float
    data17: float
    data18: float
    data19: float
    lFlag: int
    strTN: str
    lIndex: int
    data_Array: str
class Mdl_jc_LoadV2_Arc_Show:
    ID: int
    LdCaseID: int
    lID: int
    nbg: int
    ned: int
    cenx: float
    ceny: float
    rad: float
    bga: float
    eda: float
    fN: float
    fMx: float
    fMy: float
    fQx: float
    fQy: float
    nDwFlag: int
class Mdl_jc_LoadV2_Line_Cal:
    ID: int
    LdCaseID: int
    lID: int
    fN: float
    fMx: float
    fMy: float
    fQx: float
    fQy: float
    nDwFlag: int
    jcAdd: int
    lCustom: int
class Mdl_jc_LoadV2_Line_Show:
    ID: int
    LdCaseID: int
    lID: int
    nbg: int
    ned: int
    bgx: float
    bgy: float
    edx: float
    edy: float
    fN: float
    fMx: float
    fMy: float
    fQx: float
    fQy: float
    nDwFlag: int
class Mdl_jc_LoadV2_LoadCase:
    ID: int
    nIndex: int
    nID: int
    nLDKind: int
    nLDCaseID: int
    nLDCaseOld: int
    nXFC: int
    strName: str
    nDwFlag: int
    nFeaLcID: int
class Mdl_jc_LoadV2_Point:
    ID: int
    LdCaseID: int
    NodeID: int
    fN: float
    fMx: float
    fMy: float
    fQx: float
    fQy: float
    nDwFlag: int
    lCustom: int
class Mdl_jc_LoadZhuHe:
    ID: int
    XiShu_1_0: float
    XiShu_1_1: float
    XiShu_1_2: float
    XiShu_1_3: float
    XiShu_1_4: float
    XiShu_1_5: float
    XiShu_1_6: float
    XiShu_1_7: float
    XiShu_1_8: float
    XiShu_1_9: float
    XiShu_1_10: float
    XiShu_1_11: float
    XiShu_1_12: float
    XiShu_1_13: float
    XiShu_1_14: float
    XiShu_1_15: float
    XiShu_1_16: float
    XiShu_1_17: float
    XiShu_1_18: float
    XiShu_1_19: float
    XiShu_1_20: float
    XiShu_1_21: float
    XiShu_1_22: float
    XiShu_1_23: float
    XiShu_1_24: float
    XiShu_1_25: float
    XiShu_1_26: float
    XiShu_1_27: float
    XiShu_1_28: float
    XiShu_1_29: float
    XiShu_1_30: float
    XiShu_1_31: float
    XiShu_1_32: float
    XiShu_1_33: float
    XiShu_1_34: float
    XiShu_1_35: float
    XiShu_1_36: float
    XiShu_1_37: float
    XiShu_2_0: float
    XiShu_2_1: float
    XiShu_2_2: float
    XiShu_2_3: float
    XiShu_2_4: float
    XiShu_2_5: float
    XiShu_2_6: float
    XiShu_2_7: float
    XiShu_2_8: float
    XiShu_2_9: float
    XiShu_2_10: float
    XiShu_2_11: float
    XiShu_2_12: float
    XiShu_2_13: float
    XiShu_2_14: float
    XiShu_2_15: float
    XiShu_2_16: float
    XiShu_2_17: float
    XiShu_2_18: float
    XiShu_2_19: float
    XiShu_2_20: float
    XiShu_2_21: float
    XiShu_2_22: float
    XiShu_2_23: float
    XiShu_2_24: float
    XiShu_2_25: float
    XiShu_2_26: float
    XiShu_2_27: float
    XiShu_2_28: float
    XiShu_2_29: float
    XiShu_2_30: float
    XiShu_2_31: float
    XiShu_2_32: float
    XiShu_2_33: float
    XiShu_2_34: float
    XiShu_2_35: float
    XiShu_2_36: float
    XiShu_2_37: float
    nFuHao0: int
    nFuHao1: int
    nFuHao2: int
    nFuHao3: int
    nFuHao4: int
    nFuHao5: int
    nFuHao6: int
    nFuHao7: int
    nFuHao8: int
    nFuHao9: int
    nFuHao10: int
    nFuHao11: int
    nFuHao12: int
    nFuHao13: int
    nFuHao14: int
    nFuHao15: int
    nFuHao16: int
    nFuHao17: int
    nFuHao18: int
    nFuHao19: int
    nFuHao20: int
    nFuHao21: int
    nFuHao22: int
    nFuHao23: int
    nFuHao24: int
    nFuHao25: int
    nFuHao26: int
    nFuHao27: int
    nFuHao28: int
    nFuHao29: int
    nFuHao30: int
    nFuHao31: int
    nFuHao32: int
    nFuHao33: int
    nFuHao34: int
    nFuHao35: int
    nFuHao36: int
    nFuHao37: int
    nType: int
    nEarthQuk: int
    nWaterGK: int
    strName: str
    dWaterXS: float
    nLinearity: int
    Mark_PM_SATE: int
    nDefault: int
    XiShu_1_Array: str
    XiShu_2_Array: str
    nFuHao_Array: str
    nProperties: int
class Mdl_jc_LoadZH_real:
    ID: int
    LoadIndex: int
    LoadCoef: float
    LoadName: str
class Mdl_jc_LoadZH_Float:
    ID: int
    LoadIndex: int
    LoadCoef: float
    LoadName: str
class Mdl_jc_Load_Arc:
    ID: int
    nbg: int
    ned: int
    cenx: float
    ceny: float
    rad: float
    bga: float
    eda: float
    lID: int
    fM_0: float
    fM_1: float
    fM_2: float
    fM_3: float
    fM_4: float
    fM_5: float
    fM_6: float
    fM_7: float
    fM_8: float
    fM_9: float
    fN_0: float
    fN_1: float
    fN_2: float
    fN_3: float
    fN_4: float
    fN_5: float
    fN_6: float
    fN_7: float
    fN_8: float
    fN_9: float
    fMy_0: float
    fMy_1: float
    fMy_2: float
    fMy_3: float
    fMy_4: float
    fMy_5: float
    fMy_6: float
    fMy_7: float
    fMy_8: float
    fMy_9: float
class Mdl_jc_load_Chose:
    ID: int
    nMark_Load_Chose: int
class Mdl_jc_Load_Line:
    ID: int
    nbg: int
    ned: int
    bgx: float
    bgy: float
    edx: float
    edy: float
    lID: int
    fM_0: float
    fM_1: float
    fM_2: float
    fM_3: float
    fM_4: float
    fM_5: float
    fM_6: float
    fM_7: float
    fM_8: float
    fM_9: float
    fN_0: float
    fN_1: float
    fN_2: float
    fN_3: float
    fN_4: float
    fN_5: float
    fN_6: float
    fN_7: float
    fN_8: float
    fN_9: float
    fMy_0: float
    fMy_1: float
    fMy_2: float
    fMy_3: float
    fMy_4: float
    fMy_5: float
    fMy_6: float
    fMy_7: float
    fMy_8: float
    fMy_9: float
class Mdl_jc_Load_ZiDingYi_Arc:
    ID: int
    nbg: int
    ned: int
    cenx: float
    ceny: float
    rad: float
    bga: float
    eda: float
    lID: int
    data0: float
    data1: float
    data2: float
    data3: float
    data4: float
    data5: float
    data6: float
    data7: float
    data8: float
    data9: float
    data10: float
    data11: float
    data12: float
    data13: float
    data14: float
    data15: float
    data16: float
    data17: float
    data18: float
    data19: float
    data_Array: str
class Mdl_jc_load_ZiDingYi_Line:
    ID: int
    nbg: int
    ned: int
    bgx: float
    bgy: float
    edx: float
    edy: float
    lID: int
    data0: int
    data1: int
    data2: int
    data3: int
    data4: int
    data5: int
    data6: int
    data7: int
    data8: int
    data9: int
    data10: int
    data11: int
    data12: int
    data13: int
    data14: int
    data15: int
    data16: int
    data17: int
    data18: int
    data19: int
    data_Array: str
class Mdl_jc_ParaNums:
    ID: int
    Nums_LoadZhuHe: int
    Nums_Points_All: int
    Nums_Grid_Line: int
    Nums_Grid_Arc: int
    njan: int
    naxis: int
    Nums_Col: int
    Nums_Col_Sec: int
    Nums_Wall_UP: int
    Nums_Wall_Sec: int
    Nums_Load_Line: int
    Nums_Load_Arc: int
    Mark_Soil_Use: int
    Mark_Water_Use: int
    Nums_ZiDingYi_Dead: int
    Nums_ZiDingYi_Live: int
    cMark_Dead: str
    cMark_Live: str
    Mark_Soil_Have: int
    Mark_Water_Have: int
    Str_ZiDingYi_Dead: str
    Str_ZiDingYi_Live: str
    cc: int
    ccc: int
class Mdl_jc_Points_Load:
    ID: int
    lNJ: int
    lIndex: int
    Ang: float
    fLiveLoad_Blp: float
class Mdl_jc_RaftCornerPoint:
    ID: int
    RaftID: int
    ec1: int
    ec2: int
    ptx: float
    pty: float
    rad: int
    cx: int
    cy: int
class Mdl_jc_RaftSlab:
    ID: int
    nCeng: int
    lID: int
    nMainRaftId: int
    b_h: float
    thick: float
    BotElevat: float
    nDire: int
    padd: float
    padd_os: float
    FLD: float
    FLL: float
    RfGrade: int
    RfLoad: float
    bRfPara: int
    RebarAngle: float
    EndH: float
    isBGAbs: int
    fk: float
    amb: float
    amd: float
    InewFlag: int
    lOutB: int
    lBotH: int
    baseZ: int
    idUp: int
    SoilK: float
    DJCL_Kexi: float
    DJCL_Thick: float
    fk_Euro: float
class Mdl_jc_RaftYInfo:
    ID: int
    x1: float
    y1: float
    z1: float
    x2: float
    y2: float
    z2: float
    B: float
    H: float
    lDir: int
    dOffsetL: float
class Mdl_jc_ZiDingYi_Name:
    ID: int
    nType: int
    cName: str
class Mdl_jc_ChildRaft:
    ID: int
    dFLD: float
    dFLL: float
    dRigidity: float
    padd: float
    X: str
    Y: str
    dCX: float
    dCY: float
    vecCustomLoad: str
    listGrid: str
    vecData: str
    nIndexPoolRoom: int
class Mdl_JcResultData_Py:
    m_jcResultAntifloatRaftList: list[Mdl_jcResult_antifloat_Raft]
    m_jcResultGeoFeaElemList: list[Mdl_jcResult_geo_FeaElem]
    m_jcResultGeoFeaPointList: list[Mdl_jcResult_geo_FeaPoint]
    m_jcResultGeoGridList: list[Mdl_jcResult_geo_Grid]
    m_jcResultGeoNodeList: list[Mdl_jcResult_geo_Node]
    m_jcResultGeoRoomList: list[Mdl_jcResult_geo_Room]
    m_jcResultInforceCTList: list[Mdl_jcResult_inforce_CT]
    m_jcResultInforceCTBeamList: list[Mdl_jcResult_inforce_CTBeam]
    m_jcResultInforceDJList: list[Mdl_jcResult_inforce_DJ]
    m_jcResultInforceFBeamList: list[Mdl_jcResult_inforce_FBeam]
    m_jcResultInforceFeaElemList: list[Mdl_jcResult_inforce_FeaElem]
    m_jcResultInforceLLList: list[Mdl_jcResult_inforce_LL]
    m_jcResultLoadCaseList: list[Mdl_jcResult_load_Case]
    m_jcResultLoadCombList: list[Mdl_jcResult_load_Comb]
    m_jcResultLocalcompressCTList: list[Mdl_jcResult_localcompress_CT]
    m_jcResultLocalcompressDJList: list[Mdl_jcResult_localcompress_DJ]
    m_jcResultLocalcompressFBeamList: list[Mdl_jcResult_localcompress_FBeam]
    m_jcResultLocalcompressRaftList: list[Mdl_jcResult_localcompress_Raft]
    m_jcResultPunchCTList: list[Mdl_jcResult_punch_CT]
    m_jcResultPunchDJList: list[Mdl_jcResult_punch_DJ]
    m_jcResultPunchRaftList: list[Mdl_jcResult_punch_Raft]
    m_jcResultReactionDJList: list[Mdl_jcResult_reaction_DJ]
    m_jcResultReactionFBeamList: list[Mdl_jcResult_reaction_FBeam]
    m_jcResultReactionFeaElemList: list[Mdl_jcResult_reaction_FeaElem]
    m_jcResultReactionPileList: list[Mdl_jcResult_reaction_Pile]
    m_jcResultReactionRaftList: list[Mdl_jcResult_reaction_Raft]
    m_jcResultReinCTList: list[Mdl_jcResult_rein_CT]
    m_jcResultReinCTBeamList: list[Mdl_jcResult_rein_CTBeam]
    m_jcResultReinCTTriList: list[Mdl_jcResult_rein_CT_Tri]
    m_jcResultReinDJList: list[Mdl_jcResult_rein_DJ]
    m_jcResultReinFBeamList: list[Mdl_jcResult_rein_FBeam]
    m_jcResultReinLLList: list[Mdl_jcResult_rein_LL]
    m_jcResultSettleCTList: list[Mdl_jcResult_settle_CT]
    m_jcResultSettleDJList: list[Mdl_jcResult_settle_DJ]
    m_jcResultSettleFBeamList: list[Mdl_jcResult_settle_FBeam]
    m_jcResultSettleFeaElemList: list[Mdl_jcResult_settle_FeaElem]
    m_jcResultSettlePileList: list[Mdl_jcResult_settle_Pile]
    m_jcResultSettleRaftList: list[Mdl_jcResult_settle_Raft]
    m_jcResultSettleTotalCTList: list[Mdl_jcResult_settle_total_CT]
    m_jcResultSettleTotalDJList: list[Mdl_jcResult_settle_total_DJ]
    m_jcResultSettleTotalFBeamList: list[Mdl_jcResult_settle_total_FBeam]
    m_jcResultSettleTotalPileList: list[Mdl_jcResult_settle_total_Pile]
    m_jcResultSettleTotalRaftList: list[Mdl_jcResult_settle_total_Raft]
    m_jcResultShearCTList: list[Mdl_jcResult_shear_CT]
    m_jcResultShearCTBeamList: list[Mdl_jcResult_shear_CTBeam]
    m_jcResultShearDJList: list[Mdl_jcResult_shear_DJ]
    m_jcResultSoilcapDJList: list[Mdl_jcResult_soilcap_DJ]
    m_jcResultSoilcapFBeamList: list[Mdl_jcResult_soilcap_FBeam]
    m_jcResultSoilcapFeaElemList: list[Mdl_jcResult_soilcap_FeaElem]
    m_jcResultSoilcapPileList: list[Mdl_jcResult_soilcap_Pile]
    m_jcResultSoilcapRaftList: list[Mdl_jcResult_soilcap_Raft]
    m_jcResultTotalloadCTList: list[Mdl_jcResult_totalload_CT]
    m_jcResultTotalloadDJList: list[Mdl_jcResult_totalload_DJ]
    m_jcResultTotalloadRaftList: list[Mdl_jcResult_totalload_Raft]
    m_jcResultVerList: list[Mdl_jcResult_ver]
class Mdl_JcResultData:
    m_jcResultAntifloatRaftList: list[Mdl_jcResult_antifloat_Raft]
    m_jcResultGeoFeaElemList: list[Mdl_jcResult_geo_FeaElem]
    m_jcResultGeoFeaPointList: list[Mdl_jcResult_geo_FeaPoint]
    m_jcResultGeoGridList: list[Mdl_jcResult_geo_Grid]
    m_jcResultGeoNodeList: list[Mdl_jcResult_geo_Node]
    m_jcResultGeoRoomList: list[Mdl_jcResult_geo_Room]
    m_jcResultInforceCTList: list[Mdl_jcResult_inforce_CT]
    m_jcResultInforceCTBeamList: list[Mdl_jcResult_inforce_CTBeam]
    m_jcResultInforceDJList: list[Mdl_jcResult_inforce_DJ]
    m_jcResultInforceFBeamList: list[Mdl_jcResult_inforce_FBeam]
    m_jcResultInforceFeaElemList: list[Mdl_jcResult_inforce_FeaElem]
    m_jcResultInforceLLList: list[Mdl_jcResult_inforce_LL]
    m_jcResultLoadCaseList: list[Mdl_jcResult_load_Case]
    m_jcResultLoadCombList: list[Mdl_jcResult_load_Comb]
    m_jcResultLocalcompressCTList: list[Mdl_jcResult_localcompress_CT]
    m_jcResultLocalcompressDJList: list[Mdl_jcResult_localcompress_DJ]
    m_jcResultLocalcompressFBeamList: list[Mdl_jcResult_localcompress_FBeam]
    m_jcResultLocalcompressRaftList: list[Mdl_jcResult_localcompress_Raft]
    m_jcResultPunchCTList: list[Mdl_jcResult_punch_CT]
    m_jcResultPunchDJList: list[Mdl_jcResult_punch_DJ]
    m_jcResultPunchRaftList: list[Mdl_jcResult_punch_Raft]
    m_jcResultReactionDJList: list[Mdl_jcResult_reaction_DJ]
    m_jcResultReactionFBeamList: list[Mdl_jcResult_reaction_FBeam]
    m_jcResultReactionFeaElemList: list[Mdl_jcResult_reaction_FeaElem]
    m_jcResultReactionPileList: list[Mdl_jcResult_reaction_Pile]
    m_jcResultReactionRaftList: list[Mdl_jcResult_reaction_Raft]
    m_jcResultReinCTList: list[Mdl_jcResult_rein_CT]
    m_jcResultReinCTBeamList: list[Mdl_jcResult_rein_CTBeam]
    m_jcResultReinCTTriList: list[Mdl_jcResult_rein_CT_Tri]
    m_jcResultReinDJList: list[Mdl_jcResult_rein_DJ]
    m_jcResultReinFBeamList: list[Mdl_jcResult_rein_FBeam]
    m_jcResultReinLLList: list[Mdl_jcResult_rein_LL]
    m_jcResultSettleCTList: list[Mdl_jcResult_settle_CT]
    m_jcResultSettleDJList: list[Mdl_jcResult_settle_DJ]
    m_jcResultSettleFBeamList: list[Mdl_jcResult_settle_FBeam]
    m_jcResultSettleFeaElemList: list[Mdl_jcResult_settle_FeaElem]
    m_jcResultSettlePileList: list[Mdl_jcResult_settle_Pile]
    m_jcResultSettleRaftList: list[Mdl_jcResult_settle_Raft]
    m_jcResultSettleTotalCTList: list[Mdl_jcResult_settle_total_CT]
    m_jcResultSettleTotalDJList: list[Mdl_jcResult_settle_total_DJ]
    m_jcResultSettleTotalFBeamList: list[Mdl_jcResult_settle_total_FBeam]
    m_jcResultSettleTotalPileList: list[Mdl_jcResult_settle_total_Pile]
    m_jcResultSettleTotalRaftList: list[Mdl_jcResult_settle_total_Raft]
    m_jcResultShearCTList: list[Mdl_jcResult_shear_CT]
    m_jcResultShearCTBeamList: list[Mdl_jcResult_shear_CTBeam]
    m_jcResultShearDJList: list[Mdl_jcResult_shear_DJ]
    m_jcResultSoilcapDJList: list[Mdl_jcResult_soilcap_DJ]
    m_jcResultSoilcapFBeamList: list[Mdl_jcResult_soilcap_FBeam]
    m_jcResultSoilcapFeaElemList: list[Mdl_jcResult_soilcap_FeaElem]
    m_jcResultSoilcapPileList: list[Mdl_jcResult_soilcap_Pile]
    m_jcResultSoilcapRaftList: list[Mdl_jcResult_soilcap_Raft]
    m_jcResultTotalloadCTList: list[Mdl_jcResult_totalload_CT]
    m_jcResultTotalloadDJList: list[Mdl_jcResult_totalload_DJ]
    m_jcResultTotalloadRaftList: list[Mdl_jcResult_totalload_Raft]
    m_jcResultVerList: list[Mdl_jcResult_ver]
    def ToPyList(self) -> Mdl_JcResultData_Py: ...
class Mdl_jcResult_antifloat_Raft:
    ID: int
    G: float
    Sigma_Rt: float
    Nwk: float
    Kw: float
class Mdl_jcResult_geo_FeaElem:
    ID: int
    npt_0: int
    npt_1: int
    npt_2: int
    npt_3: int
    nRaft_CT_DJ: int
class Mdl_jcResult_geo_FeaPoint:
    ID: int
    ptx: float
    pty: float
    ptz: float
class Mdl_jcResult_geo_Grid:
    ID: int
    nbg: int
    ned: int
    ngrid: int
class Mdl_jcResult_geo_Node:
    ID: int
    X: float
    Y: float
    Z: float
class Mdl_jcResult_geo_Room:
    ID: int
    ang: float
    nodes: str
    grids: str
class Mdl_jcResult_inforce_CT:
    ID: int
    Comb: int
    IsFea: int
    Mx_bot: float
    My_bot: float
    Mx_top: float
    My_top: float
class Mdl_jcResult_inforce_CTBeam:
    ID: int
    Comb: int
    M: float
    V: float
class Mdl_jcResult_inforce_DJ:
    ID: int
    Comb: int
    IsFea: int
    Mx_bot: float
    My_bot: float
    Mx_top: float
    My_top: float
class Mdl_jcResult_inforce_FBeam:
    ID: int
    Comb: int
    M_Sec_I: float
    M_Sec_1: float
    M_Sec_2: float
    M_Sec_3: float
    M_Sec_4: float
    M_Sec_5: float
    M_Sec_6: float
    M_Sec_7: float
    M_Sec_J: float
    V_Sec_I: float
    V_Sec_1: float
    V_Sec_2: float
    V_Sec_3: float
    V_Sec_4: float
    V_Sec_5: float
    V_Sec_6: float
    V_Sec_7: float
    V_Sec_J: float
class Mdl_jcResult_inforce_FeaElem:
    ID: int
    Comb: int
    Mx: float
    My: float
    Qx: float
    Qy: float
class Mdl_jcResult_inforce_LL:
    ID: int
    Comb: int
    M_Sec_I: float
    M_Sec_1: float
    M_Sec_2: float
    M_Sec_3: float
    M_Sec_4: float
    M_Sec_5: float
    M_Sec_6: float
    M_Sec_7: float
    M_Sec_J: float
    V_Sec_I: float
    V_Sec_1: float
    V_Sec_2: float
    V_Sec_3: float
    V_Sec_4: float
    V_Sec_5: float
    V_Sec_6: float
    V_Sec_7: float
    V_Sec_J: float
class Mdl_jcResult_load_Case:
    ID: int
    nLDKind: int
    strName: str
class Mdl_jcResult_load_Comb:
    ID: int
    nType: int
    nLinearity: int
    CaseID: int
    Xishu: float
class Mdl_jcResult_localcompress_CT:
    ID: int
    Type: int
    ComponentID: int
    Fl: float
    Comb: int
    RS: float
class Mdl_jcResult_localcompress_DJ:
    ID: int
    Type: int
    ComponentID: int
    Fl: float
    Comb: int
    RS: float
class Mdl_jcResult_localcompress_FBeam:
    ID: int
    Type: int
    ComponentID: int
    Fl: float
    Comb: int
    RS: float
class Mdl_jcResult_localcompress_Raft:
    ID: int
    Type: int
    ComponentID: int
    Fl: float
    Comb: int
    RS: float
class Mdl_jcResult_punch_CT:
    ID: int
    Type: int
    ComponentID: int
    Fl: float
    Comb: int
    RS: float
class Mdl_jcResult_punch_DJ:
    ID: int
    SecID: int
    Step: int
    Direct: int
    Fl: float
    Comb: int
    RS: float
class Mdl_jcResult_punch_Raft:
    ID: int
    Type: int
    ComponentID: int
    Fl: float
    Comb: int
    RS: float
class Mdl_jcResult_reaction_DJ:
    ID: int
    Comb: int
    Comb_type: int
    pkmax: float
    pkmin: float
    pkavg: float
class Mdl_jcResult_reaction_FBeam:
    ID: int
    Comb: int
    Comb_type: int
    pkmax: float
    pkmin: float
    pkavg: float
class Mdl_jcResult_reaction_FeaElem:
    ID: int
    Comb: int
    Comb_type: int
    pk: float
class Mdl_jcResult_reaction_Pile:
    ID: int
    Comb: int
    Comb_type: int
    verti_force: float
    hori_force_x: float
    hori_force_y: float
class Mdl_jcResult_reaction_Raft:
    ID: int
    Comb: int
    Comb_type: int
    pkmax: float
    pkmin: float
    pkavg: float
class Mdl_jcResult_rein_CT:
    ID: int
    Style: int
    Asx_top: float
    Ratiox_top: float
    Mx_top: float
    Asx_bot: float
    Ratiox_bot: float
    Mx_bot: float
    Asy_top: float
    Ratioy_top: float
    My_top: float
    Asy_bot: float
    Ratioy_bot: float
    My_bot: float
class Mdl_jcResult_rein_CTBeam:
    ID: int
    Method: int
    As_bot: float
    Rs_bot: float
    Asv: float
    Rsv: float
    Ash: float
    Rsh: float
    M: float
    V: float
class Mdl_jcResult_rein_CT_Tri:
    ID: int
    Style: int
    As1: float
    Rs1: float
    M1: float
    As2: float
    Rs2: float
    M2: float
class Mdl_jcResult_rein_DJ:
    ID: int
    Style: int
    Asx_top: float
    Ratiox_top: float
    Mx_top: float
    Asx_bot: float
    Ratiox_bot: float
    Mx_bot: float
    Asy_top: float
    Ratioy_top: float
    My_top: float
    Asy_bot: float
    Ratioy_bot: float
    My_bot: float
class Mdl_jcResult_rein_FBeam:
    ID: int
    Type: int
    Asu: list[float]
    Rsu: list[float]
    Mu: list[float]
    Asd: list[float]
    Rsd: list[float]
    Md: list[float]
    Asyy: list[float]
    Rsyy: list[float]
    Myy: list[float]
    Ashyy: list[float]
    Rshyy: list[float]
    Mhyy: list[float]
    Asv: list[float]
    Rsv: list[float]
    Vmax: list[float]
class Mdl_jcResult_rein_LL:
    ID: int
    Asu: list[float]
    Rsu: list[float]
    Mu: list[float]
    Asd: list[float]
    Rsd: list[float]
    Md: list[float]
    Asv: list[float]
    Rsv: list[float]
    Vmax: list[float]
class Mdl_jcResult_settle_CT:
    ID: int
    LayerID: int
    Es: float
    Thick: float
    Sigma: float
    si: float
class Mdl_jcResult_settle_DJ:
    ID: int
    LayerID: int
    Es: float
    Thick: float
    Sigma: float
    si: float
class Mdl_jcResult_settle_FBeam:
    ID: int
    LayerID: int
    Es: float
    Thick: float
    Sigma: float
    si: float
class Mdl_jcResult_settle_FeaElem:
    ID: int
    LayerID: int
    Es: float
    Thick: float
    Sigma: float
    si: float
class Mdl_jcResult_settle_Pile:
    ID: int
    LayerID: int
    Es: float
    Thick: float
    Sigma: float
    si: float
class Mdl_jcResult_settle_Raft:
    ID: int
    LayerID: int
    Es: float
    Thick: float
    Sigma: float
    si: float
class Mdl_jcResult_settle_total_CT:
    ID: int
    TotalLoad: float
    Area: float
    Pc: float
    P0: float
    fi: float
    fi_e: float
    ss: float
    s_final: float
class Mdl_jcResult_settle_total_DJ:
    ID: int
    TotalLoad: float
    Area: float
    Pc: float
    P0: float
    fi: float
    ss: float
    s_final: float
class Mdl_jcResult_settle_total_FBeam:
    ID: int
    SoilR: float
    Pc: float
    P0: float
    fi: float
    ss: float
    s_final: float
class Mdl_jcResult_settle_total_Pile:
    ID: int
    Qj: float
    kxi_e: float
    se: float
    fi: float
    ss: float
    s_final: float
class Mdl_jcResult_settle_total_Raft:
    ID: int
    TotalLoad: float
    Area: float
    Pc: float
    P0: float
    fi: float
    ss: float
    s_final: float
class Mdl_jcResult_shear_CT:
    ID: int
    SecID: int
    Type: int
    Angle: float
    Vs: float
    Comb: int
    RS: float
class Mdl_jcResult_shear_CTBeam:
    ID: int
    SecID: int
    Method: int
    Angle: float
    bVmax: int
    Vs: float
    Comb: int
    RS: float
class Mdl_jcResult_shear_DJ:
    ID: int
    SecID: int
    Step: int
    Direct: int
    IsNeed: int
    Vs: float
    Comb: int
    RS: float
class Mdl_jcResult_soilcap_DJ:
    ID: int
    fa: float
    faE: float
    faW: float
class Mdl_jcResult_soilcap_FBeam:
    ID: int
    fa: float
    faE: float
    faW: float
class Mdl_jcResult_soilcap_FeaElem:
    ID: int
    fa: float
    faE: float
    faW: float
class Mdl_jcResult_soilcap_Pile:
    ID: int
    Ra: float
    Rh: float
    Rt: float
class Mdl_jcResult_soilcap_Raft:
    ID: int
    fa: float
    faE: float
    faW: float
class Mdl_jcResult_totalload_CT:
    ID: int
    LoadCase: int
    N: float
    Mx: float
    My: float
    Qx: float
    Qy: float
class Mdl_jcResult_totalload_DJ:
    ID: int
    LoadCase: int
    N: float
    Mx: float
    My: float
    Qx: float
    Qy: float
class Mdl_jcResult_totalload_Raft:
    ID: int
    LoadCase: int
    N: float
    Mx: float
    My: float
    Qx: float
    Qy: float
class Mdl_jcResult_ver:
    ID: int
    version: str
class Hi_DbModelData_Py:
    m_StdFlr: list[Mdl_StdFlr]
    m_StdFlrPara: list[Mdl_StdFlrPara]
    m_Floor: list[Mdl_Floor]
    m_Axis: list[Mdl_Axis]
    m_Grid: list[Mdl_Grid]
    m_Group: list[Mdl_Group]
    m_Joint: list[Mdl_Joint]
    m_WallSect: list[Mdl_WallSect]
    m_WallSeg: list[Mdl_WallSeg]
    m_WallHoleDef: list[Mdl_WallHoleDef]
    m_WallHole: list[Mdl_WallHole]
    m_BeamSect: list[Mdl_BeamSect]
    m_BeamHoleSect: list[Mdl_BeamHoleSect]
    m_BeamSeg: list[Mdl_BeamSeg]
    m_BeamHoleSeg: list[Mdl_BeamHoleSeg]
    m_SubBeam: list[Mdl_SubBeam]
    m_Slab: list[Mdl_Slab]
    m_MidSlab: list[Mdl_MidSlab]
    m_SlabJYDef: list[Mdl_SlabJYDef]
    m_SlabHoleDef: list[Mdl_SlabHoleDef]
    m_SlabHole: list[Mdl_SlabHole]
    m_CantiSlabDef: list[Mdl_CantiSlabDef]
    m_CantiSlab: list[Mdl_CantiSlab]
    m_ColSect: list[Mdl_ColSect]
    m_ColSeg: list[Mdl_ColSeg]
    m_ColCapSect: list[Mdl_ColCapSect]
    m_BeamJYSect: list[Mdl_BeamJY]
    m_BeamJYSeg: list[Mdl_BeamYSeg]
    m_ColCapSeg: list[Mdl_ColcapSeg]
    m_BraceSect: list[Mdl_BraceSect]
    m_BraceSeg: list[Mdl_BraceSeg]
    m_StairDef: list[Mdl_StairDef]
    m_Stair40: list[Mdl_StairSeg40]
    m_StairSeg: list[Mdl_StairSeg]
    m_LoadSect: list[Mdl_LoadSect]
    m_LoadSeg: list[Mdl_LoadSeg]
    m_ProjectPara: list[Mdl_ProjectPara]
    m_Property: list[Mdl_Property]
    m_GKLoadDef: list[Mdl_GKLoadDef]
    m_SkinLoadSect: list[Mdl_SkinLoadSect]
    m_SkinSeg: list[Mdl_SkinSeg]
    m_Crane: list[Mdl_Crane]
    m_CraneDef: list[Mdl_CraneDef]
    m_BeamJGSect: list[Mdl_BeamJGSect]
    m_ColJGSect: list[Mdl_ColJGSect]
    m_SteelJGSect: list[Mdl_SteelJGSect]
    m_JGSeg: list[Mdl_JGSeg]
    m_XNQSeg: list[Mdl_XNQSeg]
    m_XNQSegSect: list[Mdl_XNQSect]
    m_FillWallSect: list[Mdl_FillWallDef]
    m_FillWallSeg: list[Mdl_FillWall]
    unionID: int
class Hi_DbModelData:
    m_StdFlr: list[Mdl_StdFlr]
    m_StdFlrPara: list[Mdl_StdFlrPara]
    m_Floor: list[Mdl_Floor]
    m_Axis: list[Mdl_Axis]
    m_Grid: list[Mdl_Grid]
    m_Group: list[Mdl_Group]
    m_Joint: list[Mdl_Joint]
    m_WallSect: list[Mdl_WallSect]
    m_WallSeg: list[Mdl_WallSeg]
    m_WallHoleDef: list[Mdl_WallHoleDef]
    m_WallHole: list[Mdl_WallHole]
    m_BeamSect: list[Mdl_BeamSect]
    m_BeamHoleSect: list[Mdl_BeamHoleSect]
    m_BeamSeg: list[Mdl_BeamSeg]
    m_BeamHoleSeg: list[Mdl_BeamHoleSeg]
    m_SubBeam: list[Mdl_SubBeam]
    m_Slab: list[Mdl_Slab]
    m_MidSlab: list[Mdl_MidSlab]
    m_SlabJYDef: list[Mdl_SlabJYDef]
    m_SlabHoleDef: list[Mdl_SlabHoleDef]
    m_SlabHole: list[Mdl_SlabHole]
    m_CantiSlabDef: list[Mdl_CantiSlabDef]
    m_CantiSlab: list[Mdl_CantiSlab]
    m_ColSect: list[Mdl_ColSect]
    m_ColSeg: list[Mdl_ColSeg]
    m_ColCapSect: list[Mdl_ColCapSect]
    m_BeamJYSect: list[Mdl_BeamJY]
    m_BeamJYSeg: list[Mdl_BeamYSeg]
    m_ColCapSeg: list[Mdl_ColcapSeg]
    m_BraceSect: list[Mdl_BraceSect]
    m_BraceSeg: list[Mdl_BraceSeg]
    m_StairDef: list[Mdl_StairDef]
    m_Stair40: list[Mdl_StairSeg40]
    m_StairSeg: list[Mdl_StairSeg]
    m_LoadSect: list[Mdl_LoadSect]
    m_LoadSeg: list[Mdl_LoadSeg]
    m_ProjectPara: list[Mdl_ProjectPara]
    m_Property: list[Mdl_Property]
    m_GKLoadDef: list[Mdl_GKLoadDef]
    m_SkinLoadSect: list[Mdl_SkinLoadSect]
    m_SkinSeg: list[Mdl_SkinSeg]
    m_Crane: list[Mdl_Crane]
    m_CraneDef: list[Mdl_CraneDef]
    m_BeamJGSect: list[Mdl_BeamJGSect]
    m_ColJGSect: list[Mdl_ColJGSect]
    m_SteelJGSect: list[Mdl_SteelJGSect]
    m_JGSeg: list[Mdl_JGSeg]
    m_XNQSeg: list[Mdl_XNQSeg]
    m_XNQSegSect: list[Mdl_XNQSect]
    m_FillWallSect: list[Mdl_FillWallDef]
    m_FillWallSeg: list[Mdl_FillWall]
    unionID: int
    def ToPyList(self) -> Hi_DbModelData_Py: ...
    def ConvertCSharpListToPythonList(self, csharpList: Any) -> PyList: ...
class Hi_UpdateInfo:
    DeleteIdList: list[int]
    DeletePropertyIdList: list[Mdl_Property]
    AddIdSet: None[int]
    AddIdSet_Property: None[int]
    AddIdSet_Grp: None[str]
    ModifyIdSet: None[int]
    ModifyIdSet_Property: None[int]
    m_gjlist: list[Any]
    unionID: int
    def Clear(self) -> None: ...
    def AddObj(self, obj: Any) -> None: ...
    def AddGrpObj(self, obj: Any) -> None: ...
    def ModifyObj(self, obj: Any) -> None: ...
    def DeleteObj(self, obj: Any) -> None: ...
    def DeleteProerty(self, property: Mdl_Property) -> None: ...
class Mdl_StdFlr:
    ID: int
    No: int
    Height: int
    Name: str
    Para: str
    LiveLoad: float
    DeadLoad: float
class Mdl_StdFlrPara:
    nStdFlrID: int
    nKind: int
    dParas: float
class Mdl_Floor:
    ID: int
    No: int
    Name: str
    StdFlrID: int
    LevelB: int
    Height: int
class Mdl_Axis:
    ID: int
    No: int
    StdFlrID: int
    Jt1ID: int
    Jt2ID: int
    Name: str
class Mdl_Grid:
    ID: int
    No: int
    StdFlrID: int
    Jt1ID: int
    Jt2ID: int
    AxisID: int
class Mdl_Group:
    No_: int
    nCnt: int
    nID: list[int]
    Name: str
    idNewZRC: list[int]
class Mdl_Joint:
    ID: int
    No: int
    StdFlrID: int
    X: float
    Y: float
    HDiff: float
class Mdl_WallSect:
    ID: int
    No: int
    Mat: int
    Kind: int
    B: int
    H: int
    T2: int
    Dis: int
    colsect1: str
    colShapeVal1: str
    colsect2: str
    colShapeVal2: str
    Name: str
class Mdl_WallSeg:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    GridID: int
    Ecc: int
    HDiff1: int
    HDiff2: int
    HDiffB: int
    sloping: int
    EccDown: int
    offset1: int
    offset2: int
    HDiffB2: int
class Mdl_WallHoleDef:
    ID: int
    No: int
    B: int
    H: int
    K: int
    Name: str
    OutLT: int
    OutLB: int
    BWT: int
    BWB: int
    HW: int
    LZW: int
    LYW: int
    LZSW: int
    LYSW: int
    HSW: int
    BSW: int
    T1SW: int
    T2SW: int
    HXW: int
    BXW: int
    T1XW: int
    T2XW: int
    Special: str
class Mdl_WallHole:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    GridID: int
    Ecc: float
    HDiff: float
    FillWallId: int
    DR: int
class Mdl_Section:
    ID: int
    No: int
    Name: str
    Mat: int
    Kind: int
    ShapeVal: str
    ShapeVal1: str
class Mdl_BeamSect:
    idNew: int
    StateFlag: int
    b: int
    h: int
    u: int
    t: int
    d: int
    f: int
    l: int
    p: int
    ID: int
    No: int
    Name: str
    Mat: int
    Kind: int
    ShapeVal: str
    ShapeVal1: str
class Mdl_BeamHoleSect:
    ID: int
    No_: int
    B: int
    H: int
    K: int
    Name: str
class Mdl_BraceSect:
    ropekind: int
    ropelevel: int
    ropetxml: int
    b: int
    h: int
    u: int
    t: int
    d: int
    f: int
    l: int
    p: int
    ID: int
    No: int
    Name: str
    Mat: int
    Kind: int
    ShapeVal: str
    ShapeVal1: str
class Mdl_ColSect:
    idNew: int
    StateFlag: int
    b: int
    h: int
    u: int
    t: int
    d: int
    f: int
    l: int
    p: int
    ID: int
    No: int
    Name: str
    Mat: int
    Kind: int
    ShapeVal: str
    ShapeVal1: str
class Mdl_ColCapSect:
    ID: int
    No: int
    Kind: int
    W: int
    L: int
    H: int
    SW: int
    SL: int
    SH: int
    Name: str
class Mdl_BeamSeg:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    GridID: int
    Ecc: int
    HDiff1: int
    HDiff2: int
    Rotation: float
    JYDef: str
    RevitID: int
    Ecc2: int
class Mdl_BeamHoleSeg:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    ElementID: int
    Ec: int
    Ez: int
class Mdl_SubBeam:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    X1: float
    Y1: float
    Z1: float
    X2: float
    Y2: float
    Z2: float
    Grid1ID: int
    Grid2ID: int
class Mdl_Slab:
    ID: int
    No: int
    StdFlrID: int
    GridsID: str
    VertexX: str
    VertexY: str
    VertexZ: str
    RoomIsHole: int
    Thickness: int
    cc: int
    dead: float
    live: float
    TransWay: int
    Ang1: float
    Ang2: float
    nEdge: int
    EdgeSupport: str
    Shape: int
    xc: float
    yc: float
    HollowSlabID: float
    PrecastSlabID: str
    PrecastSlabRebarPara: str
    SingleSeamB: int
    SingleSeamBMax: int
    PairSeamB: int
    PairSeamBMax: int
    TwoWaySlab: int
    PrecastSlabLastL: float
    PrecastSlabRotate: int
    PrecastSlabStyle_PK: int
    PrecastSlabOffsetX: int
    PrecastSlabOffsetY: int
    PrecastSlabX: str
    PrecastSlabY: str
    PrecastSlabIndex: int
    PrecastSlabCount: int
    PrecastSlabArrangeNo: str
    PrecastSlabArrangeWidth: str
    precastSlabSpace: str
    PrecastSlabParaArr: str
    ProfilSlabDefId: int
    ProfilSlabAng: float
    ProfilSlabConcertW: float
    ProfilSlabWorkLoad: float
    ProfilSlabbhou: float
    HollowBoxPtNum: int
    HollowBoxPtX: str
    HollowBoxPtY: str
    HollowBoxPtZ: str
    HollowPtOrig: str
    HollowVX: str
    HollowVY: str
    HollowOhterData: str
    PcSlabStPt: str
    PcSlabEdPt: str
class Mdl_MidSlab:
    numsPt: str
    MidPt: str
    FloorH: int
    ID: int
    No: int
    StdFlrID: int
    GridsID: str
    VertexX: str
    VertexY: str
    VertexZ: str
    RoomIsHole: int
    Thickness: int
    cc: int
    dead: float
    live: float
    TransWay: int
    Ang1: float
    Ang2: float
    nEdge: int
    EdgeSupport: str
    Shape: int
    xc: float
    yc: float
    HollowSlabID: float
    PrecastSlabID: str
    PrecastSlabRebarPara: str
    SingleSeamB: int
    SingleSeamBMax: int
    PairSeamB: int
    PairSeamBMax: int
    TwoWaySlab: int
    PrecastSlabLastL: float
    PrecastSlabRotate: int
    PrecastSlabStyle_PK: int
    PrecastSlabOffsetX: int
    PrecastSlabOffsetY: int
    PrecastSlabX: str
    PrecastSlabY: str
    PrecastSlabIndex: int
    PrecastSlabCount: int
    PrecastSlabArrangeNo: str
    PrecastSlabArrangeWidth: str
    precastSlabSpace: str
    PrecastSlabParaArr: str
    ProfilSlabDefId: int
    ProfilSlabAng: float
    ProfilSlabConcertW: float
    ProfilSlabWorkLoad: float
    ProfilSlabbhou: float
    HollowBoxPtNum: int
    HollowBoxPtX: str
    HollowBoxPtY: str
    HollowBoxPtZ: str
    HollowPtOrig: str
    HollowVX: str
    HollowVY: str
    HollowOhterData: str
    PcSlabStPt: str
    PcSlabEdPt: str
class Mdl_SlabJYDef:
    ID: int
    No: int
    Kind: int
    Para: str
    name: str
class Mdl_SlabHoleDef:
    ID: int
    No: int
    Kind: int
    ShapeVal: str
    name: str
class Mdl_SlabHole:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    JtID: int
    SlabID: int
    EccX: int
    EccY: int
    Rotation: float
class Mdl_CantiSlabDef:
    ID: int
    No: int
    Kind: int
    Length: int
    Width: int
    Thick: int
    nSubKind: int
    Para: str
    name: str
class Mdl_CantiSlab:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    GridID: int
    Thick: int
    ez: int
    ec: int
    dr: int
class Mdl_ColSeg:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    JtID: int
    EccX: int
    EccY: int
    Rotation: float
    HDiffB: int
    ColcapId: int
    Cut_Col: str
    Cut_Cap: str
    Cut_Slab: str
    RevitID: int
class Mdl_ColcapSect:
    HostID: int
    type: int
    ID: int
    No: int
    dW: int
    dH: int
    dSlabH: int
    dSlabW: int
    dSlabL: int
    dlabEW: int
    dSlabEL: int
    dcapH: int
    dcapW: int
    dcapL: int
    BRT: bool
    BRD: bool
    BLT: bool
    BLD: bool
    TRT: bool
    TRD: bool
    TLT: bool
    TLD: bool
class Mdl_ColcapSeg:
    ID: int
    HostID: int
class Mdl_BeamYSeg:
    IntanceID: int
    SymbolID: int
    HostID: int
class Mdl_BeamJY:
    type: int
    ID: int
    No: int
    dL: float
    dH1: float
    dH2: float
    dLL: float
    dLW1: float
    dLW2: float
    dRL: float
    dRW1: float
    dRW2: float
    DownVisiabe: bool
    upVisiabe: bool
    leftVisiabe: bool
    name: str
class Mdl_BraceSeg:
    ID: int
    No: int
    StdFlrID: int
    SectID: int
    Jt1ID: int
    Jt2ID: int
    EccX1: int
    EccY1: int
    HDiff1: int
    EccX2: int
    EccY2: int
    HDiff2: int
    Rotation: float
    Ex: int
    Ey: int
class Mdl_StairDef:
    ID: int
    No: int
    Col2: int
    Col3: int
    Col4: int
    Col5: int
    Col6: int
    Col7: int
    Col8: int
    Col9: int
    Col10: int
    Col11: int
    Col12: int
    Col13: int
    Col14: int
    Col15: int
    Col16: int
    Col17: int
    Col18: int
    Col19: int
    Col20: int
    Col21: int
    Col22: int
    Col23: int
    Col24: int
    Col25: int
    Col26: int
    Col27: int
    Col28: int
    Col29: int
    Col30: int
    Col31: int
    Col32: int
    Col33: int
    Col34: int
    Col35: int
    Col36: int
    Col37: int
    Col38: int
    Col39: int
    Col40: int
    Col41: int
    Col42: int
    Col43: int
    Col44: int
    Col45: int
    Col46: int
    Col47: int
    Col48: int
    Col49: int
    Col50: int
    Col51: int
    Col52: int
    Col53: int
    Col54: int
    Col55: int
    Col56: int
    Col57: int
    Col58: int
    Col59: int
    Col60: int
    Col61: int
    Col62: int
    Col63: int
    Col64: int
    Col65: int
    Col66: int
    Col67: int
    Col68: int
    Col69: int
    Col70: int
    Col71: int
    gangh: int
    TZdef: str
    TLdef: str
    LCLdef: str
    def GetDef(self) -> list[str]: ...
    def GetNData(self) -> list[int]: ...
class Mdl_StairSeg:
    ID: int
    No: int
    StdFlrID: int
    SectionID: int
    SlabID: int
    StartNode: int
    AntiClockwise: int
class Mdl_StairSeg40:
    ID: int
    No: int
    StdFlrID: int
    SectionID: int
    SlabID: int
    StartNode: int
    AntiClockwise: int
    BoxPt1x: float
    BoxPtly: float
    BoxPt1z: float
    BoxPt2x: float
    BoxPt2y: float
    BoxPt2z: float
    BoxPt3x: float
    BoxPt3y: float
    BoxPt3z: float
    BoxPt4x: float
    BoxPt4y: float
    BoxPt4z: float
class Mdl_LoadSect:
    ID: int
    No: int
    ElementKind: int
    ShapeVal: str
    strName: str
class Mdl_LoadSeg:
    ID: int
    No: int
    SectID: int
    Type: int
    ElementID: int
    strParas1: str
    nPtCnt: int
    strParasX: str
    strParasY: str
    strParasZ: str
    stdFlrID: int
class Mdl_ProjectPara:
    ID: int
    ParaVal: str
class Mdl_Property:
    ID: int
    Name: str
    Type: int
    ShapeVal: str
class Mdl_GKLoadDef:
    ID: int
    No_: int
    kind: int
    dDead: float
    nLive: int
    dLive1: float
    dLive2: float
    dLive3: float
    strName: str
    Data: str
    StateFlag: int
class Mdl_SkinLoadSect:
    ID: int
    No: int
    Kind: int
    Style: int
    Val: float
    Direction: int
class Mdl_XNQSect:
    ID: int
    No: int
    Name: str
    Mat: int
    Kind: int
    BrcidDef: int
    d1: int
    L1: int
    H1: int
    H: int
    T: int
    BrcLel: int
    BrcMar: int
    WallLel: int
    WallMar: int
    ShuBrcidDef: int
    CalPara: str
    Quality: float
class Mdl_XNQSeg:
    ID: int
    No: int
    StdFlrId: int
    SectID: int
    idNode1: int
    idNode2: int
    idGrid: int
    nd1: int
    nd2: int
    ntop: int
    nbottom: int
class Mdl_SkinSeg:
    ID: int
    No: int
    StdFlrID: int
    Dead: float
    Live: float
    Thick: int
    TotalStress: float
    MaterialStyle: int
    ConcreteLevel: float
    CustomMaterialID: int
    Direction: str
    vecPtX: str
    vecPtY: str
    vecPtZ: str
    vecNodeID: str
    vecVal: str
    vecLoadID: str
    vecInx: str
    vecNodeIDNew: str
    listLoad: str
    nDirection: str
class Mdl_Crane:
    ID: int
    No: int
    StdFlrID: int
    Jan1: int
    IDX11: int
    IDX12: int
    Jan2: int
    IDX21: int
    IDX22: int
    Ex1: float
    Ex2: float
    Hx: float
    F1: float
    F2: float
    Ez: float
    DchNum: int
    DchNo1: int
    DchNo2: int
class Mdl_CraneDef:
    ID: int
    No: int
    CraneLoadData: str
    Name: str
class Mdl_CraneLoad:
    StdFlrID: int
    Num: int
    CraneLoadData: str
    Name: str
    DchLoadInfo: list[list[float]]
class Mdl_ColJGSect:
    k: int
    ID: int
    No: int
    name: str
class Mdl_ColJG_MagnifySect:
    b_l: int
    b_r: int
    h_t: int
    h_b: int
    hnt: int
    k: int
    ID: int
    No: int
    name: str
class Mdl_ColJG_WrapSteel:
    gangh: int
    b: int
    h: float
    s: int
    pos: int
    _def: _kColumInt
    k: int
    ID: int
    No: int
    name: str
class Mdl_ColJG_Convert:
    b: int
    h: int
    hnt: int
    k: int
    ID: int
    No: int
    name: str
class Mdl_ColJG_StickPlate:
    b: int
    h: int
    t: float
    gangh: int
    k: int
    ID: int
    No: int
    name: str
class Mdl_ColJG_StickFibre:
    _k: int
    kk: int
    bw: int
    hw: int
    cw: int
    cs: int
    n: int
    t: float
    k: int
    ID: int
    No: int
    name: str
class Mdl_BeamJGSect:
    k: int
    ID: int
    No: int
    name: str
class Mdl_BeamJG_MagnifySect:
    b: int
    hb: int
    ht: int
    hnt: int
    steelB: str
    steelT: str
    steelH: str
    k: int
    ID: int
    No: int
    name: str
class Mdl_BeamJG_Convert:
    hb: int
    ht: int
    hnt: int
    k: int
    ID: int
    No: int
    name: str
class Mdl_BeamJG_WrapSteel:
    cw: int
    ct: float
    cs: int
    gangh: int
    defb: _kColumInt
    deft: _kColumInt
    bw: int
    bt: int
    k: int
    ID: int
    No: int
    name: str
class Mdl_BeamJG_StickPlate:
    bw: int
    bt: float
    tw: int
    tt: float
    cw: int
    ct: float
    cs: int
    gangh: int
    k: int
    ID: int
    No: int
    name: str
class Mdl_BeamJG_StickFibre:
    _k: int
    kk: int
    bn: int
    bw: int
    tn: int
    tw: int
    cn: int
    cs: int
    cw: int
    t: float
    k: int
    ID: int
    No: int
    name: str
class Mdl_BeamJG_ReinForceSteelStrand:
    r: float
    cs: int
    Hrl: int
    Srw: int
    Szj: int
    k: int
    ID: int
    No: int
    name: str
class Mdl_BeamJG_StickPlateAndMagnifySect:
    tw: int
    tt: float
    gangh: int
    b: int
    hb: int
    hnt: int
    k: int
    ID: int
    No: int
    name: str
class Mdl_SteelJGSect:
    ID: int
    No_: int
    idNew: int
    Name: str
    k: int
    SteelLevel: int
    SHFS: float
    HJCC: float
    HDCD: float
    HDJG: float
    B1: float
    B2: float
    T1: float
    T2: float
    SubK: int
    TSecK: int
    IsXY: int
    IsInter: int
    Dmid: int
    SectionSteelName: str
class Mdl_JGSeg:
    ID: int
    No_: int
    StdFlrID: int
    ElementKind: int
    SectID: int
    ElementID: int
class Mdl_FillWall:
    ID: int
    StdFlrID: int
    SectID: int
    x1: float
    y1: float
    dR: float
    x2: float
    y2: float
    Ea: int
    Ez: int
    Ez1: int
    Ez2: int
    GridId: int
    EccDown: int
    Height: int
    Ez3: int
class Mdl_FillWallDef:
    ID: int
    FireProtectClass: int
    Name: str
    RongZhong: int
    FillMainMat: int
    Thick: int
    Height: int
    K: int
    FuncType: int
    KZJ: int
    E: float
    U: float
    tFillWallType: int