# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gravi/models/rhino-compute.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'gravi/models/rhino-compute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gs_options_pb2 as gs__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n gravi/models/rhino-compute.proto\x12\x0cgravi.models\x1a\x10gs-options.proto\"l\n\x0cRhinoRequest\x12\x11\n\tprocessId\x18\x01 \x01(\t\x12\x38\n\x0f\x64\x65\x63imateRequest\x18\n \x01(\x0b\x32\x1d.gravi.models.DecimateRequestH\x00:\x04\x88\xb5\x18\x01\x42\t\n\x07request\"p\n\rRhinoResponse\x12\x11\n\tprocessId\x18\x01 \x01(\t\x12:\n\x10\x64\x65\x63imateResponse\x18\n \x01(\x0b\x32\x1e.gravi.models.DecimateResponseH\x00:\x04\x88\xb5\x18\x01\x42\n\n\x08response\"m\n\x0f\x44\x65\x63imateRequest\x12\x16\n\x0esourceFilePath\x18\x02 \x01(\t\x12\x0f\n\x07postfix\x18\x03 \x01(\t\x12\x17\n\x0ftargetFaceCount\x18\x04 \x01(\x05\x12\x12\n\nexportPath\x18\x05 \x01(\t:\x04\x88\xb5\x18\x01\"Z\n\x10\x44\x65\x63imateResponse\x12,\n\x06result\x18\x01 \x01(\x0e\x32\x1c.gravi.models.DecimateResult\x12\x12\n\nexportPath\x18\x05 \x01(\t:\x04\x88\xb5\x18\x01*\x9c\x01\n\x0e\x44\x65\x63imateResult\x12\x19\n\x15\x44\x65\x63imateResultUnknown\x10\x00\x12\x19\n\x15\x44\x65\x63imateResultSuccess\x10\x01\x12\x18\n\x14\x44\x65\x63imateResultFailed\x10\x02\x12\x1c\n\x18\x44\x65\x63imateResultNoResource\x10\x03\x12\x1c\n\x18\x44\x65\x63imateResultProcessing\x10\x04\x42P\n\x18\x63om.gravitysketch.modelsP\x01Z2gravitysketch.com/platform/go/vrproto/gravi/modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gravi.models.rhino_compute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.gravitysketch.modelsP\001Z2gravitysketch.com/platform/go/vrproto/gravi/models'
  _globals['_RHINOREQUEST']._loaded_options = None
  _globals['_RHINOREQUEST']._serialized_options = b'\210\265\030\001'
  _globals['_RHINORESPONSE']._loaded_options = None
  _globals['_RHINORESPONSE']._serialized_options = b'\210\265\030\001'
  _globals['_DECIMATEREQUEST']._loaded_options = None
  _globals['_DECIMATEREQUEST']._serialized_options = b'\210\265\030\001'
  _globals['_DECIMATERESPONSE']._loaded_options = None
  _globals['_DECIMATERESPONSE']._serialized_options = b'\210\265\030\001'
  _globals['_DECIMATERESULT']._serialized_start=496
  _globals['_DECIMATERESULT']._serialized_end=652
  _globals['_RHINOREQUEST']._serialized_start=68
  _globals['_RHINOREQUEST']._serialized_end=176
  _globals['_RHINORESPONSE']._serialized_start=178
  _globals['_RHINORESPONSE']._serialized_end=290
  _globals['_DECIMATEREQUEST']._serialized_start=292
  _globals['_DECIMATEREQUEST']._serialized_end=401
  _globals['_DECIMATERESPONSE']._serialized_start=403
  _globals['_DECIMATERESPONSE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
