# Generated by Django 5.1.7 on 2025-03-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender_net', '0004_alter_newslettercampaign_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendernetsettings',
            name='api_key',
            field=models.CharField(help_text='Sender.net API key (get from Sender.net dashboard)', max_length=300, verbose_name='API Key'),
        ),
    ]
