from __future__ import annotations

from .vertical import Vertical

__all__ = ["ND"]

class ND:
    def __eq__(self, arg0: ND) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def to_long_string(self) -> str: ...
    def to_short_string(self) -> str: ...
    @property
    def lhs(self) -> Vertical: ...
    @property
    def lhs_indices(self) -> list[int]: ...
    @property
    def rhs(self) -> Vertical: ...
    @property
    def rhs_indices(self) -> list[int]: ...
    @property
    def weight(self) -> int: ...
