import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_dd14ebbf05(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_61893307c9():spartaqube_cli.list()
@app.command()
def sparta_92f3cf0619():spartaqube_cli.sparta_92f3cf0619()
@app.command()
def sparta_4e2cbbf043():print('Hello world!')
if __name__=='__main__':app()