# Error Tags

FOR_LOOP_INCORRECT_NUMBER_OF_ITERATIONS = "FOR_LOOP_INCORRECT_NUMBER_OF_ITERATIONS"
FOR_LOOP_MISSING = "FOR_LOOP_MISSING"
FOR_LOOP_BODY_MISMATCH = "FOR_LOOP_BODY_MISMATCH"
MISSING_STATEMENT = "MISSING_STATEMENT"
ERROR_VALUE_PARAMETER = "ERROR_VALUE_PARAMETER"

# Annotation Tags

ANNOTATION_TAG_CONST_VALUE_MISMATCH = "CONST_VALUE_MISMATCH"
ANNOTATION_TAG_MISSING_FOR_LOOP = "MISSING_FOR_LOOP"
ANNOTATION_TGA_MISSING = "MISSING"

# Annotation Contexts

ANNOTATION_CONTEXT_FOR_LOOP_BODY = "Module > For > Body"

# This regex checks if the context ends with a pattern like:
# "Call: <any_text> > Const: <any_text>"
ANNOTATION_CONTEXT_FUNCTION_PARAMETER = r"Call:\s*.+\s*>\s*Const:\s*.+\s*$"




