from __future__ import annotations
from . import algorithms

__all__ = [
    "AscCanonicalOD",
    "DescCanonicalOD",
    "ListOD",
    "SimpleCanonicalOD",
    "algorithms",
]

class AscCanonicalOD:
    def __eq__(self, arg0: AscCanonicalOD) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...

class DescCanonicalOD:
    def __eq__(self, arg0: DescCanonicalOD) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...

class ListOD:
    @property
    def lhs(self) -> list[int]: ...
    @property
    def rhs(self) -> list[int]: ...

class SimpleCanonicalOD:
    def __eq__(self, arg0: SimpleCanonicalOD) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
