# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gravi/unity/unity-log.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'gravi/unity/unity-log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gs_options_pb2 as gs__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgravi/unity/unity-log.proto\x12\x0bgravi.unity\x1a\x10gs-options.proto\"\x9a\x03\n\x08UnityLog\x12\x10\n\x08logLevel\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x03\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\tsessionId\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x14\n\x0cversionMajor\x18\x06 \x01(\x05\x12\x14\n\x0cversionMinor\x18\x07 \x01(\x05\x12\x15\n\rversionHotfix\x18\x08 \x01(\x05\x12\x15\n\rversionLetter\x18\t \x01(\t\x12\x0c\n\x04gsid\x18\n \x01(\t\x12\x13\n\x0bunityUserId\x18\x0b \x01(\t\x12\r\n\x05orgId\x18\x0c \x01(\t\x12\x0e\n\x06roomId\x18\r \x01(\t\x12\x11\n\trequestId\x18\x0e \x01(\t\x12\x14\n\x0croomClientId\x18\x0f \x01(\x05\x12\x11\n\tmaxMemory\x18\x10 \x01(\x02\x12\x12\n\nmaxTexture\x18\x11 \x01(\x02\x12\x12\n\nstackTrace\x18\x12 \x01(\t\x12\x11\n\tclassName\x18\x13 \x01(\t\x12\x0b\n\x03\x65rr\x18\x14 \x01(\t\x12\x0e\n\x05level\x18\xe8\x07 \x01(\t:\x04\x88\xb5\x18\x01\"I\n\x10\x42\x61tchedUnityLogs\x12#\n\x04logs\x18\x01 \x03(\x0b\x32\x15.gravi.unity.UnityLog\x12\x10\n\x08pingTest\x18\x02 \x01(\x08\x42\\\n%com.gravitysketch.sketch.unity.loggerP\x01Z1gravitysketch.com/platform/go/vrproto/gravi/unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gravi.unity.unity_log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.gravitysketch.sketch.unity.loggerP\001Z1gravitysketch.com/platform/go/vrproto/gravi/unity'
  _globals['_UNITYLOG']._loaded_options = None
  _globals['_UNITYLOG']._serialized_options = b'\210\265\030\001'
  _globals['_UNITYLOG']._serialized_start=63
  _globals['_UNITYLOG']._serialized_end=473
  _globals['_BATCHEDUNITYLOGS']._serialized_start=475
  _globals['_BATCHEDUNITYLOGS']._serialized_end=548
# @@protoc_insertion_point(module_scope)
