from __future__ import annotations
import desbordante
from . import algorithms

__all__ = ["ARStrings", "ArAlgorithm", "ArIDs", "algorithms"]

class ARStrings:
    def __str__(self) -> str: ...
    @property
    def confidence(self) -> float: ...
    @property
    def left(self) -> list[str]: ...
    @property
    def right(self) -> list[str]: ...
    @property
    def support(self) -> float: ...

class ArAlgorithm(desbordante.Algorithm):
    def get_ar_ids(self) -> list[ArIDs]: ...
    def get_ars(self) -> list[ARStrings]: ...
    def get_itemnames(self) -> list[str]: ...

class ArIDs:
    @property
    def confidence(self) -> float: ...
    @property
    def left(self) -> list[int]: ...
    @property
    def right(self) -> list[int]: ...
    @property
    def support(self) -> float: ...
