# Generated by Django 5.1.7 on 2025-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210625_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryenvelope',
            name='future_publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryenvelope',
            name='future_publish_processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
