# Generated by Django 4.2.13 on 2024-06-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0010_alter_eveindustryactivityduration_eve_type_and_more'),
        ('marketmanager', '0055_alter_marginconfig_destination_solar_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginconfig',
            name='destination_station',
            field=models.ManyToManyField(blank=True, related_name='+', to='eveuniverse.evestation', verbose_name='Destination Station'),
        ),
        migrations.AddField(
            model_name='marginconfig',
            name='source_station',
            field=models.ManyToManyField(blank=True, related_name='+', to='eveuniverse.evestation', verbose_name='Source Station'),
        ),
    ]
