# This file was auto-generated by Fern from our API Definition.

import typing
from .templates_create_agents_response_agents_item_tools_item_metadata_item import (
    TemplatesCreateAgentsResponseAgentsItemToolsItemMetadataItem,
)

TemplatesCreateAgentsResponseAgentsItemToolsItemMetadata = typing.Union[
    typing.Optional[typing.Any],
    typing.Optional[str],
    typing.List[typing.Optional[TemplatesCreateAgentsResponseAgentsItemToolsItemMetadataItem]],
]
