# Generated by Django 4.2.4 on 2023-09-18 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import sparkplug_core.models.subscriber_mixin
import sparkplug_videos.uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False)),
                ('file', models.FileField(null=True, upload_to=sparkplug_videos.uploads.file_location)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['uuid'], name='sparkplug_v_uuid_780f74_idx')],
            },
            bases=(sparkplug_core.models.subscriber_mixin.SubscriberMixin, models.Model),
        ),
    ]
