# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kody_clientsdk_python.ecom.v1 import ecom_pb2 as com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in com/kodypay/grpc/ecom/v1/ecom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KodyEcomPaymentsServiceStub(object):
    """All service requests require X-API-Key header with 'API Key' value
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiatePayment = channel.unary_unary(
                '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/InitiatePayment',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationResponse.FromString,
                _registered_method=True)
        self.InitiatePaymentStream = channel.unary_stream(
                '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/InitiatePaymentStream',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.FromString,
                _registered_method=True)
        self.PaymentDetails = channel.unary_unary(
                '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/PaymentDetails',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.FromString,
                _registered_method=True)
        self.PaymentDetailsStream = channel.unary_stream(
                '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/PaymentDetailsStream',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.FromString,
                _registered_method=True)
        self.GetPayments = channel.unary_unary(
                '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/GetPayments',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetPaymentsRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetPaymentsResponse.FromString,
                _registered_method=True)
        self.GetCardToken = channel.unary_unary(
                '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/GetCardToken',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetCardTokenRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetCardTokenResponse.FromString,
                _registered_method=True)
        self.Refund = channel.unary_stream(
                '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/Refund',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.RefundRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.RefundResponse.FromString,
                _registered_method=True)


class KodyEcomPaymentsServiceServicer(object):
    """All service requests require X-API-Key header with 'API Key' value
    """

    def InitiatePayment(self, request, context):
        """Initiates a payment and returns a URL for the user to complete payment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiatePaymentStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PaymentDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PaymentDetailsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCardToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refund(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KodyEcomPaymentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiatePayment,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationResponse.SerializeToString,
            ),
            'InitiatePaymentStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InitiatePaymentStream,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.SerializeToString,
            ),
            'PaymentDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.PaymentDetails,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.SerializeToString,
            ),
            'PaymentDetailsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PaymentDetailsStream,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.SerializeToString,
            ),
            'GetPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayments,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetPaymentsRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetPaymentsResponse.SerializeToString,
            ),
            'GetCardToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCardToken,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetCardTokenRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetCardTokenResponse.SerializeToString,
            ),
            'Refund': grpc.unary_stream_rpc_method_handler(
                    servicer.Refund,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.RefundRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.RefundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KodyEcomPaymentsService(object):
    """All service requests require X-API-Key header with 'API Key' value
    """

    @staticmethod
    def InitiatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/InitiatePayment',
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiatePaymentStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/InitiatePaymentStream',
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentInitiationRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PaymentDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/PaymentDetails',
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PaymentDetailsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/PaymentDetailsStream',
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.PaymentDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/GetPayments',
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetPaymentsRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetPaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCardToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/GetCardToken',
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetCardTokenRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.GetCardTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refund(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.kodypay.grpc.ecom.v1.KodyEcomPaymentsService/Refund',
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.RefundRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ecom_dot_v1_dot_ecom__pb2.RefundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
