"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TestCommand(google.protobuf.message.Message):
    """This file is reverse-engineered from the generated test_command_pb2.py.

    A simple message with one string field.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEST_DATA_FIELD_NUMBER: builtins.int
    test_data: builtins.str
    def __init__(
        self,
        *,
        test_data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["test_data", b"test_data"]) -> None: ...

global___TestCommand = TestCommand
