from enum import Enum


class ContentGenerationRequestPiiEntityCategories(str, Enum):
    ABA_ROUTING_NUMBER = "ABARoutingNumber"
    ADDRESS = "Address"
    ARGENTINA_NATIONAL_IDENTITY_DNI_NUMBER = "ARNationalIdentityNumber"
    AUSTRALIAN_BUSINESS_NUMBER = "AUBusinessNumber"
    AUSTRALIA_BANK_ACCOUNT_NUMBER = "AUBankAccountNumber"
    AUSTRALIA_COMPANY_NUMBER = "AUCompanyNumber"
    AUSTRALIA_DRIVERS_LICENSE = "AUDriversLicenseNumber"
    AUSTRALIA_MEDICAL_ACCOUNT_NUMBER = "AUMedicalAccountNumber"
    AUSTRALIA_PASSPORT_NUMBER = "AUPassportNumber"
    AUSTRALIA_TAX_FILE_NUMBER = "AUTaxFileNumber"
    AUSTRIA_IDENTITY_CARD = "ATIdentityCard"
    AUSTRIA_TAX_IDENTIFICATION_NUMBER = "ATTaxIdentificationNumber"
    AUSTRIA_VALUE_ADDED_TAX_VAT_NUMBER = "ATValueAddedTaxNumber"
    BELGIUM_NATIONAL_NUMBER = "BENationalNumber"
    BELGIUM_NATIONAL_NUMBER_V2 = "BENationalNumberV2"
    BELGIUM_VALUE_ADDED_TAX_VAT_NUMBER = "BEValueAddedTaxNumber"
    BRAZIL_CPF_NUMBER = "BRCPFNumber"
    BRAZIL_LEGAL_ENTITY_NUMBER_CNPJ = "BRLegalEntityNumber"
    BRAZIL_NATIONAL_ID_CARD_RG = "BRNationalIDRG"
    CANADA_BANK_ACCOUNT_NUMBER = "CABankAccountNumber"
    CANADA_DRIVERS_LICENSE_NUMBER = "CADriversLicenseNumber"
    CANADA_HEALTH_SERVICE_NUMBER = "CAHealthServiceNumber"
    CANADA_PASSPORT_NUMBER = "CAPassportNumber"
    CANADA_PERSONAL_HEALTH_IDENTIFICATION_NUMBER_PHIN = "CAPersonalHealthIdentification"
    CANADA_SOCIAL_INSURANCE_NUMBER = "CASocialInsuranceNumber"
    CHILE_IDENTITY_CARD_NUMBER = "CLIdentityCardNumber"
    CHINA_RESIDENT_IDENTITY_CARD_PRC_NUMBER = "CNResidentIdentityCardNumber"
    CREDIT_CARD = "CreditCardNumber"
    DATE_TIME = "DateTime"
    EMAIL = "Email"
    EUGPS_COORDINATES = "EUGPSCoordinates"
    EU_DEBIT_CARD_NUMBER = "EUDebitCardNumber"
    EU_DRIVERS_LICENSE_NUMBER = "EUDriversLicenseNumber"
    EU_NATIONAL_IDENTIFICATION_NUMBER = "EUNationalIdentificationNumber"
    EU_PASSPORT_NUMBER = "EUPassportNumber"
    EU_SOCIAL_SECURITY_NUMBER_SSN_OR_EQUIVALENT_ID = "EUSocialSecurityNumber"
    EU_TAX_IDENTIFICATION_NUMBER_TIN = "EUTaxIdentificationNumber"
    FRANCE_DRIVERS_LICENSE_NUMBER = "FRDriversLicenseNumber"
    FRANCE_HEALTH_INSURANCE_NUMBER = "FRHealthInsuranceNumber"
    FRANCE_NATIONAL_ID_CARD_CNI = "FRNationalID"
    FRANCE_PASSPORT_NUMBER = "FRPassportNumber"
    FRANCE_SOCIAL_SECURITY_NUMBER_INSEE = "FRSocialSecurityNumber"
    FRANCE_TAX_IDENTIFICATION_NUMBER_NUM_É_RO_SPI = "FRTaxIdentificationNumber"
    FRANCE_VALUE_ADDED_TAX_VAT_NUMBER = "FRValueAddedTaxNumber"
    GERMANY_IDENTITY_CARD_NUMBER = "DEIdentityCardNumber"
    GERMANY_PASSPORT_NUMBER = "DEPassportNumber"
    GERMANY_TAX_IDENTIFICATION_NUMBER = "DETaxIdentificationNumber"
    GERMANY_VALUE_ADDED_TAX_NUMBER = "DEValueAddedNumber"
    GERMAN_DRIVERS_LICENSE_NUMBER = "DEDriversLicenseNumber"
    HONG_KONG_IDENTITY_CARD_HKID_NUMBER = "HUPersonalIdentificationNumber"
    HUNGARY_TAX_IDENTIFICATION_NUMBER = "HUTaxIdentificationNumber"
    HUNGARY_VALUE_ADDED_TAX_NUMBER = "HUValueAddedNumber"
    INDIA_PERMANENT_ACCOUNT_NUMBER_PAN = "INPermanentAccount"
    INDIA_UNIQUE_IDENTIFICATION_AADHAAR_NUMBER = "INUniqueIdentificationNumber"
    INDONESIA_IDENTITY_CARD_KTP_NUMBER = "IDIdentityCardNumber"
    INTERNATIONAL_BANKING_ACCOUNT_NUMBER = "InternationalBankingAccountNumber"
    IP_ADDRESS = "IPAddress"
    IRELAND_PERSONAL_PUBLIC_SERVICE_PPS_NUMBER = "IEPersonalPublicServiceNumber"
    IRELAND_PERSONAL_PUBLIC_SERVICE_PPS_NUMBER_V2 = "IEPersonalPublicServiceNumberV2"
    ISRAEL_BANK_ACCOUNT_NUMBER = "ILBankAccountNumber"
    ISRAEL_NATIONAL_ID = "ILNationalID"
    ITALY_DRIVERS_LICENSE_ID = "ITDriversLicenseNumber"
    ITALY_FISCAL_CODE = "ITFiscalCode"
    JAPAN_BANK_ACCOUNT_NUMBER = "JPBankAccountNumber"
    JAPAN_DRIVERS_LICENSE_NUMBER = "JPDriversLicenseNumber"
    JAPAN_MY_NUMBER_CORPORATE = "JPMyNumberCorporate"
    JAPAN_MY_NUMBER_PERSONAL = "JPMyNumberPersonal"
    JAPAN_RESIDENCE_CARD_NUMBER = "JPResidenceCardNumber"
    JAPAN_RESIDENT_REGISTRATION_NUMBER = "ITValueAddedTaxNumber"
    JAPAN_SOCIAL_INSURANCE_NUMBER_SIN = "JPSocialInsuranceNumber"
    LUXEMBOURG_NATIONAL_IDENTIFICATION_NUMBER_NATURAL_PERSONS = (
        "LUNationalIdentificationNumberNatural"
    )
    LUXEMBOURG_NATIONAL_IDENTIFICATION_NUMBER_NON_NATURAL_PERSONS = (
        "LUNationalIdentificationNumberNonNatural"
    )
    MALTA_IDENTITY_CARD_NUMBER = "MTIdentityCardNumber"
    MALTA_TAX_IDENTIFICATION_NUMBER = "MTTaxIDNumber"
    NEW_ZEALAND_BANK_ACCOUNT_NUMBER = "NZBankAccountNumber"
    NEW_ZEALAND_DRIVERS_LICENSE_NUMBER = "NZDriversLicenseNumber"
    NEW_ZEALAND_INLAND_REVENUE_NUMBER = "NZInlandRevenueNumber"
    NEW_ZEALAND_MINISTRY_OF_HEALTH_NUMBER = "NZMinistryOfHealthNumber"
    NEW_ZEALAND_SOCIAL_WELFARE_NUMBER = "NZSocialWelfareNumber"
    ORGANIZATION = "Organization"
    PERSON = "Person"
    PERSON_TYPE = "PersonType"
    PHILIPPINES_UNIFIED_MULTI_PURPOSE_ID_NUMBER = "PHUnifiedMultiPurposeIDNumber"
    PHONE_NUMBER = "PhoneNumber"
    PORTUGAL_CITIZEN_CARD_NUMBER = "PTCitizenCardNumber"
    PORTUGAL_TAX_IDENTIFICATION_NUMBER = "PTTaxIdentificationNumber"
    QUANTITY = "Quantity"
    SOUTH_AFRICA_IDENTIFICATION_NUMBER = "ZAIdentificationNumber"
    SOUTH_KOREA_RESIDENT_REGISTRATION_NUMBER = "KRResidentRegistrationNumber"
    SPAIN_DNI = "ESDNI"
    SPAIN_SOCIAL_SECURITY_NUMBER_SSN = "ESSocialSecurityNumber"
    SPAIN_TAX_IDENTIFICATION_NUMBER = "ESTaxIdentificationNumber"
    SWIFT_CODE = "SWIFTCode"
    SWISS_SOCIAL_SECURITY_NUMBER_AHV = "CHSocialSecurityNumber"
    TAIWAN_NATIONAL_ID = "TWNationalID"
    TAIWAN_PASSPORT_NUMBER = "TWPassportNumber"
    TAIWAN_RESIDENT_CERTIFICATE_ARCTARC = "TWResidentCertificate"
    UK_DRIVERS_LICENSE_NUMBER = "UKDriversLicenseNumber"
    UK_NATIONAL_HEALTH_SERVICE_NHS_NUMBER = "UKNationalHealthNumber"
    UK_NATIONAL_INSURANCE_NUMBER_NINO = "UKNationalInsuranceNumber"
    UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER = "UKUniqueTaxpayerNumber"
    URL = "URL"
    US_BANK_ACCOUNT_NUMBER = "USBankAccountNumber"
    US_DRIVERS_LICENSE_NUMBER = "USDriversLicenseNumber"
    US_DRUG_ENFORCEMENT_AGENCY_DEA_NUMBER = "DrugEnforcementAgencyNumber"
    US_INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER_ITIN = (
        "USIndividualTaxpayerIdentification"
    )
    US_OR_UK_PASSPORT_NUMBER = "USUKPassportNumber"
    US_SOCIAL_SECURITY_NUMBER_SSN = "USSocialSecurityNumber"

    def __str__(self) -> str:
        return str(self.value)
