
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-25T11:22:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "69b47f417844ede95de45dcd4f82cfff2f7caf7a",
 "version": "2.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
